"""Leadership Library catalogue — 40 curated titles.

Every entry carries Sudarshan Karweer's perspective (why_sk), the key learnings
(lessons) and a practical way to turn the book into a daily RITUAL across
professional and personal life (ritual / ritual_pro / ritual_personal).

Public-domain titles carry a Project Gutenberg id (in-site reader) and, where a
verified LibriVox recording exists on the Internet Archive, a free audiobook id.
Copyrighted titles carry key lessons + an Amazon link + curated video only.
"""

BOOKS = [
    # ---------------- Public-domain classics ----------------
    {"slug": "art-of-war", "title": "The Art of War", "author": "Sun Tzu", "year": "5th c. BC",
     "theme": "Strategy", "public_domain": True, "gutenberg": "132", "audio": "artofwar_1402_librivox",
     "blurb": "The oldest and most influential treatise on strategy — competition, positioning and winning without fighting.",
     "why_sk": "The single best primer on competitive strategy I return to before every big move.",
     "lessons": ["Win before you fight — shape the ground first.", "Know yourself and know your competitor.",
                 "Speed and deception beat brute force.", "Supreme excellence is subduing rivals without a battle.",
                 "Adapt your tactics endlessly to the terrain."],
     "ritual": "Turn strategy from an event into a weekly habit of seeing the board before you touch a piece.",
     "ritual_pro": ["Every Monday, name the one 'battle' you should win this week — and the two you should refuse.",
                    "Before any negotiation, write the other side's best move first, then your counter."],
     "ritual_personal": ["Pick one conflict at home and ask: can I win this without fighting?",
                         "Sunday review — where did I burn energy on ground not worth taking?"],
     "source": "Project Gutenberg (text) · LibriVox / Internet Archive (audio), public domain.",
     "credit": "Translation by Lionel Giles. Public domain."},
    {"slug": "the-prince", "title": "The Prince", "author": "Niccolò Machiavelli", "year": "1532",
     "theme": "Power", "public_domain": True, "gutenberg": "1232", "audio": "prince_librivox",
     "blurb": "The founding text of realpolitik — how power is really won, used and kept.",
     "why_sk": "Uncomfortable but honest about how influence and authority actually work.",
     "lessons": ["It's safer to be feared than loved, if you can't be both — but never hated.",
                 "Study the moves of great leaders and adapt them.", "Fortune favours the bold and prepared.",
                 "Deliver hard news fast, good news slowly.", "Reputation is built by decisive action."],
     "ritual": "Read power clearly so you can lead cleanly — a fortnightly audit of where influence really sits.",
     "ritual_pro": ["Map your stakeholders every two weeks: who holds real power vs. a title.",
                    "Batch bad news and deliver it same-day; let good news land slowly and often."],
     "ritual_personal": ["Notice one relationship you're managing on fear, not respect — and repair it.",
                        "Keep a 'promises kept' log; your reputation is the sum of it."],
     "source": "Project Gutenberg (text) · LibriVox / Internet Archive (audio), public domain.",
     "credit": "Translation by W. K. Marriott. Public domain."},
    {"slug": "meditations", "title": "Meditations", "author": "Marcus Aurelius", "year": "180 AD",
     "theme": "Leadership & Stoicism", "public_domain": True, "gutenberg": "2680", "audio": "meditations_0708_librivox",
     "blurb": "The private journal of a Roman emperor — the definitive manual on self-mastery and calm command.",
     "why_sk": "My go-to for keeping perspective and composure under pressure.",
     "lessons": ["You have power over your mind — not outside events.", "Waste no time arguing what a good leader should be; be one.",
                 "The obstacle is the way.", "Do the right thing; the rest doesn't matter.", "Focus only on what you control."],
     "ritual": "A two-minute journal, morning and night, is how self-mastery becomes automatic.",
     "ritual_pro": ["Start the day writing the one obstacle you'll turn into progress.",
                    "End the day naming what was in your control and what wasn't — and letting the rest go."],
     "ritual_personal": ["Before reacting at home, take one breath and ask 'is this mine to control?'",
                        "Keep a gratitude line each night; perspective is a practice, not a mood."],
     "source": "Project Gutenberg (text) · LibriVox / Internet Archive (audio), public domain.",
     "credit": "Translation by Meric Casaubon. Public domain."},
    {"slug": "tao-te-ching", "title": "Tao Te Ching", "author": "Lao Tzu", "year": "4th c. BC",
     "theme": "Servant Leadership", "public_domain": True, "gutenberg": "216", "audio": "",
     "blurb": "The classic on effortless, servant leadership — leading by stepping back.",
     "why_sk": "A powerful counter-weight to hustle culture: lead by enabling, not controlling.",
     "lessons": ["The best leaders are barely known by their people.", "Lead by serving, not commanding.",
                 "Yield to overcome.", "Know when enough is enough.", "Empty yourself to be filled."],
     "ritual": "Practise 'leading less' — a weekly habit of removing yourself so others rise.",
     "ritual_pro": ["Each week, hand one decision you'd normally make to someone on your team.",
                    "In meetings, speak last; let the room fill the silence first."],
     "ritual_personal": ["Do one thing slowly and fully each day — no second screen.",
                        "Ask 'is this enough?' before adding more to your plate."],
     "source": "Project Gutenberg (text), public domain.",
     "credit": "Translation by James Legge. Public domain."},
    {"slug": "walden", "title": "Walden", "author": "Henry David Thoreau", "year": "1854",
     "theme": "Focus & Simplicity", "public_domain": True, "gutenberg": "205", "audio": "walden_librivox",
     "blurb": "A meditation on deliberate living — stripping life to essentials to find what truly matters.",
     "why_sk": "The antidote to busyness: it forces you to ask what all the effort is actually for.",
     "lessons": ["Simplify, simplify — most of what we chase is optional.", "The cost of a thing is the life you trade for it.",
                 "Wealth is the ability to fully experience life.", "Go confidently in the direction of your dreams.",
                 "Solitude sharpens judgement."],
     "ritual": "Turn 'deliberate living' into a recurring subtraction habit, not a one-time cleanse.",
     "ritual_pro": ["Once a month, cut one recurring meeting or report that no longer earns its cost.",
                    "Before saying yes, price it in hours of your life, not just money."],
     "ritual_personal": ["Keep one screen-free hour a day for a walk or thinking.",
                        "Quarterly, give away or clear one category of things you don't use."],
     "source": "Project Gutenberg (text) · LibriVox / Internet Archive (audio), public domain.",
     "credit": "Public domain."},
    {"slug": "as-a-man-thinketh", "title": "As a Man Thinketh", "author": "James Allen", "year": "1903",
     "theme": "Mindset", "public_domain": True, "gutenberg": "4507", "audio": "",
     "blurb": "A short, potent classic on how thought shapes character, circumstance and achievement.",
     "why_sk": "A 30-minute read that quietly rewires how you talk to yourself.",
     "lessons": ["You become what you repeatedly think.", "Circumstance reveals character; it doesn't create it.",
                 "Calmness of mind is strength.", "Clear thought precedes clear achievement.",
                 "Master your mind and you master your life."],
     "ritual": "Guard the quality of your thinking daily — it compounds like interest.",
     "ritual_pro": ["Reframe one setback each day as data, not a verdict.",
                    "Set a single clear intention before opening your inbox."],
     "ritual_personal": ["Catch one negative self-talk loop a day and rewrite the sentence.",
                        "End the day noting one thought that served you and one that didn't."],
     "source": "Project Gutenberg (text), public domain.",
     "credit": "Public domain."},
    {"slug": "the-republic", "title": "The Republic", "author": "Plato", "year": "375 BC",
     "theme": "Justice & Governance", "public_domain": True, "gutenberg": "1497", "audio": "",
     "blurb": "The foundational work on justice, leadership and the ideal society — the philosopher-king.",
     "why_sk": "Where the idea of the wise, disciplined leader begins — worth returning to.",
     "lessons": ["The unexamined life is poorly led.", "Leaders should be reluctant, not power-hungry.",
                 "Justice is each part doing its proper work.", "Educate judgement, not just skill.",
                 "The good of the whole guides the good leader."],
     "ritual": "Make examined leadership a habit — question your own motives before your team's.",
     "ritual_pro": ["Before a big call, ask: whose good does this actually serve?",
                    "Weekly, teach one thing you know to someone junior."],
     "ritual_personal": ["Keep a 'what did I learn' note after every disagreement.",
                        "Choose the harder-but-right option once a week and notice how it feels."],
     "source": "Project Gutenberg (text), public domain.",
     "credit": "Translation by Benjamin Jowett. Public domain."},
    {"slug": "wealth-of-nations", "title": "The Wealth of Nations", "author": "Adam Smith", "year": "1776",
     "theme": "Economics", "public_domain": True, "gutenberg": "3300", "audio": "",
     "blurb": "The founding text of modern economics — markets, incentives, specialisation and value.",
     "why_sk": "Read the source, not the slogans — it's far more nuanced on markets and morals than people assume.",
     "lessons": ["Specialisation multiplies output.", "Incentives quietly govern behaviour.",
                 "Value comes from exchange, not hoarding.", "Self-interest and public good can align.",
                 "Free exchange lifts the whole system."],
     "ritual": "Read the incentives in every situation — it becomes second nature with practice.",
     "ritual_pro": ["Before designing any process, ask 'what behaviour does this reward?'",
                    "Weekly, find one task to specialise or delegate for leverage."],
     "ritual_personal": ["Notice the incentives behind a habit you want to change, then redesign them.",
                        "Trade time for skill: swap one chore for something you do better."],
     "source": "Project Gutenberg (text), public domain.",
     "credit": "Public domain."},
    {"slug": "autobiography-franklin", "title": "The Autobiography of Benjamin Franklin", "author": "Benjamin Franklin", "year": "1791",
     "theme": "Self-Improvement", "public_domain": True, "gutenberg": "20203", "audio": "",
     "blurb": "The original self-improvement memoir — Franklin's method for building virtues and habits by design.",
     "why_sk": "His 13-virtues tracking is the ancestor of every habit system I recommend.",
     "lessons": ["Track a habit and it improves.", "Work on one virtue at a time.",
                 "Usefulness beats brilliance.", "Reputation is built by consistent small acts.",
                 "Reflect nightly on the day's ledger."],
     "ritual": "Franklin literally invented the daily habit tracker — borrow it directly.",
     "ritual_pro": ["Pick one professional 'virtue' (e.g. punctuality) and score it daily for a week.",
                    "Ask each morning: 'What good shall I do this day?'"],
     "ritual_personal": ["Keep a simple habit grid on the fridge; tick or cross each night.",
                        "Ask each evening: 'What good did I do this day?'"],
     "source": "Project Gutenberg (text), public domain.",
     "credit": "Public domain."},

    # ---------------- Modern / copyrighted essentials ----------------
    {"slug": "extreme-ownership", "title": "Extreme Ownership", "author": "Jocko Willink & Leif Babin", "year": "2015",
     "theme": "Ownership & Command", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "Navy SEAL combat leadership principles applied to business — leaders own everything in their world.",
     "why_sk": "The clearest mandate on accountability I give every senior leader I coach.",
     "lessons": ["Leaders own every outcome — no excuses, no blame.", "There are no bad teams, only bad leaders.",
                 "Keep the plan simple, clear and repeatable.", "Prioritise and execute — handle the highest threat first.",
                 "Decentralise command — every level must understand intent."],
     "ritual": "Ownership is a reflex you build by catching blame before it leaves your mouth.",
     "ritual_pro": ["In every setback review, start with 'what could I have owned?' before assigning cause.",
                    "End each day naming the single highest-priority task for tomorrow — do it first."],
     "ritual_personal": ["When something goes wrong at home, drop 'you' and try 'I could have…' once.",
                        "Own one thing you've been avoiding each week."],
     "source": "Buy the book (Amazon) · curated author talks on YouTube.",
     "credit": "© Jocko Willink & Leif Babin. Summary is our own; buy the book to read it."},
    {"slug": "fish", "title": "Fish! A Remarkable Way to Boost Morale", "author": "Lundin, Paul & Christensen", "year": "2000",
     "theme": "Teams & Culture", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "The Pike Place Fish Market parable on choosing your attitude and energising a team.",
     "why_sk": "A fast, memorable read for anyone trying to lift a flat team culture.",
     "lessons": ["Choose your attitude — every day.", "Play: bring energy and fun to the work.",
                 "Make their day — delight the people you serve.", "Be present — full attention to whoever's in front of you."],
     "ritual": "Energy is a daily choice — make it a visible team practice.",
     "ritual_pro": ["Open standups by 'choosing the attitude' the team wants for the day.",
                    "Make one colleague's day each morning with specific recognition."],
     "ritual_personal": ["Put the phone away and be fully present for one meal a day.",
                        "Bring a little play to one routine task you dread."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Stephen C. Lundin et al. Summary is our own."},
    {"slug": "pour-your-heart", "title": "Pour Your Heart Into It", "author": "Howard Schultz", "year": "1997",
     "theme": "Purpose-led Building", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "How Starbucks was built — values, culture and scaling a brand without losing its soul.",
     "why_sk": "The definitive story of scaling with purpose and heart intact.",
     "lessons": ["Build a company your people are proud of.", "Culture is your real competitive moat.",
                 "Care for your people first; profit follows.", "Stay true to values while you scale.", "Great brands are built on authenticity."],
     "ritual": "Keep purpose in view weekly so growth never quietly hollows it out.",
     "ritual_pro": ["Each week, connect one decision back to your stated values out loud.",
                    "Invest in one person's growth every month with real time, not just budget."],
     "ritual_personal": ["Write your own 'why' on one card and re-read it every Sunday.",
                        "Do one thing this week that money can't measure."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Howard Schultz. Summary is our own."},
    {"slug": "48-laws-power", "title": "The 48 Laws of Power", "author": "Robert Greene", "year": "1998",
     "theme": "Power & Influence", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "A ruthless, historical study of power dynamics — read it to recognise the game around you.",
     "why_sk": "Read it defensively — to see the moves others make, and choose your own line.",
     "lessons": ["Never outshine the master.", "Guard your reputation with your life.",
                 "Say less than necessary.", "Command attention by being unpredictable.", "Know who you're dealing with."],
     "ritual": "Use it as a mirror, not a manual — spot the game weekly, then choose integrity.",
     "ritual_pro": ["Before a charged meeting, name the power dynamic in one sentence.",
                    "Practise saying less: cut your next email in half before sending."],
     "ritual_personal": ["Notice one manipulation attempt a week and simply refuse to play.",
                        "Guard your word; do what you said you'd do this week."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Robert Greene. Summary is our own."},
    {"slug": "shoe-dog", "title": "Shoe Dog", "author": "Phil Knight", "year": "2016",
     "theme": "Founder Grit", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "Nike founder Phil Knight's raw memoir on building an iconic company against the odds.",
     "why_sk": "The most honest founder memoir on grit, cash-crunches and belief.",
     "lessons": ["Have faith in your crazy idea — and outlast the doubt.", "Cash flow can kill even a winning company.",
                 "Hire believers, not résumés.", "Let the mission recruit for you.", "Keep going — you're closer than it feels."],
     "ritual": "Grit is built by finishing — make 'one more day' a standing rule.",
     "ritual_pro": ["Watch cash weekly, not monthly; know your runway to the day.",
                    "When you want to quit a hard project, commit to one more week first."],
     "ritual_personal": ["Keep a 'wins log' for the days doubt is loud.",
                        "Move your body daily; grit lives partly in the body."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Phil Knight. Summary is our own."},
    {"slug": "good-to-great", "title": "Good to Great", "author": "Jim Collins", "year": "2001",
     "theme": "Building Enduring Companies", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "The research classic on why some companies make the leap from good to great — and most don't.",
     "why_sk": "Level 5 leadership and the Hedgehog Concept are frameworks I use in every strategy session.",
     "lessons": ["Level 5 leaders blend humility with fierce will.", "First who, then what — get the right people on the bus.",
                 "Confront the brutal facts, keep the faith (Stockdale Paradox).", "The Hedgehog Concept: passion × best-in-world × economics.",
                 "Greatness is disciplined action compounding over time (the flywheel)."],
     "ritual": "Momentum is a flywheel — protect the few disciplined pushes that turn it.",
     "ritual_pro": ["Weekly, do one thing that pushes your flywheel and stop one thing that doesn't.",
                    "In reviews, state the brutal facts first, before the plan."],
     "ritual_personal": ["Define your personal Hedgehog: what you love, do well and get value from.",
                        "Audit your 'bus' — the people you spend time with — each quarter."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Jim Collins. Summary is our own."},
    {"slug": "start-with-why", "title": "Start With Why", "author": "Simon Sinek", "year": "2009",
     "theme": "Purpose & Vision", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "Why great leaders and brands inspire action by starting with purpose, not product.",
     "why_sk": "If your team can't state the 'why', no strategy will stick. This fixes that.",
     "lessons": ["People buy why you do it, not what you do.", "Great leaders inspire; they don't manipulate.",
                 "Clarity of why comes before how and what.", "Trust is built when actions match purpose.",
                 "The Golden Circle works from the inside out."],
     "ritual": "Lead with 'why' until it becomes the first sentence of everything you launch.",
     "ritual_pro": ["Open every pitch, brief or launch by stating the why before the what.",
                    "Weekly, check one decision against your team's stated purpose."],
     "ritual_personal": ["Write your personal why in one line; revisit monthly.",
                        "Before big commitments, ask 'does this serve my why?'"],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Simon Sinek. Summary is our own."},
    {"slug": "leaders-eat-last", "title": "Leaders Eat Last", "author": "Simon Sinek", "year": "2014",
     "theme": "Trust & Safety", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "Why the best leaders create a Circle of Safety so teams can perform without fear.",
     "why_sk": "The biology of trust — it explains why psychological safety isn't soft, it's structural.",
     "lessons": ["Leaders sacrifice for their people first.", "Safety unlocks performance.",
                 "Trust and cooperation are chemical, not just cultural.", "Short-term wins can't buy long-term loyalty.",
                 "Protect people from danger inside and out."],
     "ritual": "Build the Circle of Safety with small, repeated acts of putting people first.",
     "ritual_pro": ["Take the blame publicly and give the credit publicly, every week.",
                    "Ask one team member 'what's getting in your way?' daily."],
     "ritual_personal": ["Put your people first at home too — serve before you're served once a day.",
                        "Notice when you lead by fear and switch to safety."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Simon Sinek. Summary is our own."},
    {"slug": "five-dysfunctions", "title": "The Five Dysfunctions of a Team", "author": "Patrick Lencioni", "year": "2002",
     "theme": "Team Health", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "A leadership fable on the five dysfunctions that quietly sink teams — and how to fix them.",
     "why_sk": "The fastest diagnostic I know for why a talented team still underperforms.",
     "lessons": ["Absence of trust is the root dysfunction.", "Fear of conflict kills good decisions.",
                 "Lack of commitment breeds ambiguity.", "Avoiding accountability erodes standards.",
                 "Inattention to results is the final failure."],
     "ritual": "Team health is maintained, not achieved — build trust and conflict into the calendar.",
     "ritual_pro": ["Start meetings with real debate; treat silence as a warning sign.",
                    "Close every meeting with clear commitments and who owns them."],
     "ritual_personal": ["Practise vulnerability-based trust: admit one mistake a week openly.",
                        "Hold someone you love gently accountable to a shared goal."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Patrick Lencioni. Summary is our own."},
    {"slug": "dare-to-lead", "title": "Dare to Lead", "author": "Brené Brown", "year": "2018",
     "theme": "Courageous Leadership", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "How courage, vulnerability and values make brave leaders in an uncertain world.",
     "why_sk": "It gives language and tools to the human side of leadership most execs avoid.",
     "lessons": ["Courage and vulnerability are inseparable.", "Clear is kind; unclear is unkind.",
                 "Lean into hard conversations.", "Live your values, don't just list them.",
                 "Trust is built in small moments."],
     "ritual": "Choose the brave conversation over the comfortable silence — daily.",
     "ritual_pro": ["Have the one hard conversation you're avoiding this week — clearly and kindly.",
                    "Name your two core values and check one decision against them daily."],
     "ritual_personal": ["Say the vulnerable true thing once a day instead of armouring up.",
                        "Rumble with a feeling before acting on it."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Brené Brown. Summary is our own."},
    {"slug": "hard-thing", "title": "The Hard Thing About Hard Things", "author": "Ben Horowitz", "year": "2014",
     "theme": "Hard Decisions", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "A brutally honest guide to running a company when there are no easy answers.",
     "why_sk": "The realest book on the loneliness of the top job and making calls with no good options.",
     "lessons": ["There's no recipe for the hard things.", "Take care of people, products and profits — in that order.",
                 "Tell it like it is; face the fear.", "Manage your own psychology first.",
                 "Sometimes you must fight for the company's life."],
     "ritual": "Build the muscle for hard calls by making the small ones fast and honest.",
     "ritual_pro": ["When facing a no-good-option decision, write both bad outcomes, then choose and move.",
                    "Manage your own head daily — a short walk before the hardest task."],
     "ritual_personal": ["Say the honest thing early, even when it's uncomfortable.",
                        "Separate the story from the facts when anxiety spikes."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Ben Horowitz. Summary is our own."},
    {"slug": "zero-to-one", "title": "Zero to One", "author": "Peter Thiel", "year": "2014",
     "theme": "Innovation", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "On building the future — creating something new (0→1) rather than copying (1→n).",
     "why_sk": "It sharpens the difference between real innovation and incremental competition.",
     "lessons": ["Going 0→1 beats going 1→n.", "Competition is for losers — build a monopoly of value.",
                 "Start with a small market you can dominate.", "A great question: what important truth do few agree with you on?",
                 "Sales and distribution matter as much as product."],
     "ritual": "Keep asking the contrarian question until non-consensus thinking becomes a habit.",
     "ritual_pro": ["Weekly, ask 'what do we believe that competitors don't?' and act on one.",
                    "Look for the small niche you can own completely before you scale."],
     "ritual_personal": ["Write one contrarian truth you hold each week and test it.",
                        "Build one skill that few around you have."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Peter Thiel & Blake Masters. Summary is our own."},
    {"slug": "lean-startup", "title": "The Lean Startup", "author": "Eric Ries", "year": "2011",
     "theme": "Build-Measure-Learn", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "A scientific approach to building products under uncertainty — validated learning over guesswork.",
     "why_sk": "It replaces expensive opinions with cheap experiments — essential discipline for any builder.",
     "lessons": ["Build–Measure–Learn as fast as possible.", "Ship an MVP; learn from real users.",
                 "Validated learning beats vanity metrics.", "Pivot or persevere on evidence.",
                 "Innovation accounting keeps you honest."],
     "ritual": "Turn beliefs into experiments weekly so learning outruns opinion.",
     "ritual_pro": ["Turn one assumption into a cheap test each week and read the result.",
                    "Kill one vanity metric and track a real learning metric instead."],
     "ritual_personal": ["Test a life change small before going all-in.",
                        "Weekly review: what did I actually learn, not just do?"],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Eric Ries. Summary is our own."},
    {"slug": "thinking-fast-slow", "title": "Thinking, Fast and Slow", "author": "Daniel Kahneman", "year": "2011",
     "theme": "Decision-Making", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "The Nobel laureate's masterwork on the two systems that drive how we think and decide.",
     "why_sk": "Once you see your own biases, you make far fewer expensive decision errors.",
     "lessons": ["System 1 is fast and intuitive; System 2 is slow and deliberate.", "We're overconfident and loss-averse.",
                 "Anchoring and framing quietly distort choices.", "Slow down for high-stakes decisions.",
                 "What you see is all there is — beware missing data."],
     "ritual": "Install a deliberate pause so System 2 shows up for the decisions that matter.",
     "ritual_pro": ["For any big decision, sleep on it once and list what data you're missing.",
                    "Pre-mortem one plan a month: assume it failed, ask why."],
     "ritual_personal": ["Notice one snap judgement a day and question it.",
                        "Reframe a loss as a choice about the future, not the past."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Daniel Kahneman. Summary is our own."},
    {"slug": "atomic-habits", "title": "Atomic Habits", "author": "James Clear", "year": "2018",
     "theme": "Habits & Systems", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "A proven framework for improving 1% a day — tiny changes, remarkable results.",
     "why_sk": "The most practical book on turning intentions into systems — exactly what rituals are.",
     "lessons": ["You don't rise to goals; you fall to systems.", "Make it obvious, attractive, easy, satisfying.",
                 "Habits are the compound interest of self-improvement.", "Focus on identity, not outcomes.",
                 "Environment beats willpower."],
     "ritual": "This whole library becomes a ritual using Clear's four laws — start with 'make it obvious'.",
     "ritual_pro": ["Stack a new work habit onto an existing one (after standup, I review priorities).",
                    "Design your desk/environment so the right action is the easy one."],
     "ritual_personal": ["Shrink one good habit to two minutes so it never gets skipped.",
                        "Cast a vote for your desired identity daily ('I'm a reader' → read one page)."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© James Clear. Summary is our own."},
    {"slug": "7-habits", "title": "The 7 Habits of Highly Effective People", "author": "Stephen R. Covey", "year": "1989",
     "theme": "Personal Effectiveness", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "The timeless framework for character-based effectiveness in work and life.",
     "why_sk": "Still the best operating system for a principled, proactive professional.",
     "lessons": ["Be proactive — act within your circle of influence.", "Begin with the end in mind.",
                 "Put first things first.", "Think win-win; seek first to understand.",
                 "Synergise, and sharpen the saw."],
     "ritual": "Effectiveness is weekly planning around roles and priorities, not daily firefighting.",
     "ritual_pro": ["Plan the week around big rocks first (Quadrant II), then fill the small.",
                    "Seek first to understand: paraphrase before replying in one meeting a day."],
     "ritual_personal": ["Sharpen the saw daily — one act for body, mind, heart or spirit.",
                        "Widen your circle of influence: act on what you control, release the rest."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Stephen R. Covey. Summary is our own."},
    {"slug": "how-to-win-friends", "title": "How to Win Friends and Influence People", "author": "Dale Carnegie", "year": "1936",
     "theme": "People Skills", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "The original, still-unbeaten guide to relationships, persuasion and genuine influence.",
     "why_sk": "Old but gold — the fundamentals of dealing with people never went out of date.",
     "lessons": ["Don't criticise, condemn or complain.", "Give honest, sincere appreciation.",
                 "Talk in terms of the other person's interests.", "Make people feel important — sincerely.",
                 "The only way to win an argument is to avoid it."],
     "ritual": "Practise one people-principle a day until warmth becomes default.",
     "ritual_pro": ["Give one specific, sincere appreciation to a colleague daily.",
                    "Enter meetings framing the other side's interest first."],
     "ritual_personal": ["Use people's names and ask about their world before yours.",
                        "Skip winning one argument this week; keep the relationship instead."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Dale Carnegie. Summary is our own."},
    {"slug": "drive", "title": "Drive", "author": "Daniel H. Pink", "year": "2009",
     "theme": "Motivation", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "The surprising truth about what motivates us — autonomy, mastery and purpose.",
     "why_sk": "It explains why carrots-and-sticks fail knowledge workers and what to do instead.",
     "lessons": ["Autonomy, mastery and purpose drive real motivation.", "If-then rewards can dull creative work.",
                 "Give people control over task, time, technique and team.", "Progress is the biggest daily motivator.",
                 "Purpose maximises, not just profit."],
     "ritual": "Feed autonomy, mastery and purpose in small doses to keep motivation self-renewing.",
     "ritual_pro": ["Give one person more autonomy over how they do the work this week.",
                    "Celebrate visible progress in every team meeting."],
     "ritual_personal": ["Protect one block for a mastery pursuit each week.",
                        "Reconnect a routine task to a purpose that matters to you."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Daniel H. Pink. Summary is our own."},
    {"slug": "grit", "title": "Grit", "author": "Angela Duckworth", "year": "2016",
     "theme": "Perseverance", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "Why passion and perseverance — not talent — predict long-term success.",
     "why_sk": "Talent is common; the willingness to keep going is rare and buildable.",
     "lessons": ["Grit = passion + perseverance toward long-term goals.", "Effort counts twice (skill and achievement).",
                 "Cultivate a growth mindset.", "Deliberate practice beats mere repetition.",
                 "Purpose sustains persistence."],
     "ritual": "Grit grows with deliberate practice — schedule the hard rep, don't wait for motivation.",
     "ritual_pro": ["Pick one weak skill and do a focused, uncomfortable rep on it daily.",
                    "Connect your top goal to a purpose beyond yourself and re-read it weekly."],
     "ritual_personal": ["Finish what you start this month — one thing, all the way.",
                        "Reframe 'I can't' as 'I can't yet' each time it appears."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Angela Duckworth. Summary is our own."},
    {"slug": "measure-what-matters", "title": "Measure What Matters", "author": "John Doerr", "year": "2018",
     "theme": "Goals & OKRs", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "How OKRs — Objectives and Key Results — drove Intel, Google and others to breakout growth.",
     "why_sk": "The cleanest system I've seen for aligning a whole company on what actually matters.",
     "lessons": ["Set ambitious Objectives with measurable Key Results.", "Focus and commit to priorities.",
                 "Align and connect for teamwork.", "Track for accountability.",
                 "Stretch for the amazing."],
     "ritual": "OKRs work only with a weekly check-in rhythm — make that the ritual, not the doc.",
     "ritual_pro": ["Every Monday, score last week's key results honestly and reset focus.",
                    "Keep the team to 3–5 objectives max — say no to the rest."],
     "ritual_personal": ["Set one personal objective a quarter with 2–3 measurable results.",
                        "Weekly, ask: did this week move a key result or just stay busy?"],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© John Doerr. Summary is our own."},
    {"slug": "innovators-dilemma", "title": "The Innovator's Dilemma", "author": "Clayton Christensen", "year": "1997",
     "theme": "Disruption", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "Why great companies fail by doing everything right — and how disruption really works.",
     "why_sk": "Essential for any incumbent: the things that made you successful can quietly kill you.",
     "lessons": ["Disruptive tech starts worse, then overtakes.", "Listening only to top customers can blind you.",
                 "Small markets don't solve big-company growth needs.", "Manage disruption in a separate unit.",
                 "Markets that don't exist can't be analysed — they must be explored."],
     "ritual": "Scan for disruption on a schedule; incumbents die from complacency, not stupidity.",
     "ritual_pro": ["Monthly, ask 'what cheaper, worse alternative could beat us later?'",
                    "Protect one small experiment from the core business's metrics."],
     "ritual_personal": ["Notice where you're defending a comfortable status quo.",
                        "Try the 'inferior' new tool competitors' juniors are using."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Clayton Christensen. Summary is our own."},
    {"slug": "blue-ocean", "title": "Blue Ocean Strategy", "author": "W. Chan Kim & Renée Mauborgne", "year": "2005",
     "theme": "Market Creation", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "How to make competition irrelevant by creating uncontested market space.",
     "why_sk": "Stop fighting in bloody red oceans — this shows how to build a new one instead.",
     "lessons": ["Create uncontested space (blue oceans) vs. bloody competition.", "Pursue differentiation AND low cost.",
                 "Use the four actions: eliminate, reduce, raise, create.", "Focus on non-customers.",
                 "Value innovation is the cornerstone."],
     "ritual": "Regularly redraw your strategy canvas so you're competing where no one else is.",
     "ritual_pro": ["Quarterly, run the eliminate-reduce-raise-create grid on your offering.",
                    "Study your non-customers as closely as your best ones."],
     "ritual_personal": ["Find the 'blue ocean' in your career — a mix only you offer.",
                        "Stop competing on someone else's terms in one area of life."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© W. Chan Kim & Renée Mauborgne. Summary is our own."},
    {"slug": "good-strategy", "title": "Good Strategy Bad Strategy", "author": "Richard Rumelt", "year": "2011",
     "theme": "Strategy", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "The difference between real strategy and the fluff that masquerades as it.",
     "why_sk": "It kills 'strategy' that's just goals with adjectives — and shows the real kernel.",
     "lessons": ["Strategy has a kernel: diagnosis, guiding policy, coherent action.", "Goals are not strategy.",
                 "Focus force on the decisive point.", "Bad strategy is fluff, dodged problems and mush.",
                 "Leverage comes from insight and concentration."],
     "ritual": "Pressure-test every 'strategy' against the kernel before you commit resources.",
     "ritual_pro": ["Before approving a plan, write its diagnosis, policy and actions on one page.",
                    "Concentrate resources on the single decisive point this quarter."],
     "ritual_personal": ["Turn a vague personal goal into a real strategy: what's the actual problem?",
                        "Say no to scattered effort; pick the one lever."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Richard Rumelt. Summary is our own."},
    {"slug": "principles", "title": "Principles", "author": "Ray Dalio", "year": "2017",
     "theme": "Decision Systems", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "Bridgewater's founder shares the life and work principles behind his success.",
     "why_sk": "The idea of writing down your own principles and running life like a machine is transformative.",
     "lessons": ["Embrace reality and deal with it.", "Pain + reflection = progress.",
                 "Be radically open-minded and radically transparent.", "Believe in the power of principles you write down.",
                 "Use believability-weighted decision-making."],
     "ritual": "Codify your recurring decisions into written principles you actually re-use.",
     "ritual_pro": ["Each time you solve a problem, write the principle so future-you reuses it.",
                    "After any pain point, spend five minutes reflecting to extract the lesson."],
     "ritual_personal": ["Keep a personal 'principles' doc; add one line a week.",
                        "Seek out one person who'll disagree with you honestly this week."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Ray Dalio. Summary is our own."},
    {"slug": "effective-executive", "title": "The Effective Executive", "author": "Peter F. Drucker", "year": "1966",
     "theme": "Management", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "Drucker's timeless guide to doing the right things — effectiveness as a learnable discipline.",
     "why_sk": "The father of management, distilled: effectiveness is a set of habits anyone can learn.",
     "lessons": ["Know where your time actually goes.", "Focus on contribution and results, not effort.",
                 "Build on strengths — yours and others'.", "First things first; concentrate on the few.",
                 "Make effective decisions, not popular ones."],
     "ritual": "Effectiveness is a set of daily habits — start by tracking where your time really goes.",
     "ritual_pro": ["Log your time for a week; cut the biggest low-value block.",
                    "Ask each morning: 'what can I contribute that others can't?'"],
     "ritual_personal": ["Build on a strength this week instead of fixing a weakness.",
                        "Do the most important thing first, before the day fills up."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Peter F. Drucker. Summary is our own."},
    {"slug": "radical-candor", "title": "Radical Candor", "author": "Kim Scott", "year": "2017",
     "theme": "Feedback", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "How to be a great boss by caring personally while challenging directly.",
     "why_sk": "The clearest model for feedback: neither brutal nor fake-nice, but caring and candid.",
     "lessons": ["Care personally AND challenge directly.", "Avoid ruinous empathy and obnoxious aggression.",
                 "Praise in public, criticise in private, both specifically.", "Solicit feedback before you give it.",
                 "Feedback should be immediate and kind."],
     "ritual": "Make candor a daily reflex by giving one small, caring, direct piece of feedback.",
     "ritual_pro": ["Give one specific praise and, when needed, one direct critique each day.",
                    "Ask 'what could I do better?' and sit with the silence until it's answered."],
     "ritual_personal": ["Tell someone you love a hard truth kindly this week.",
                        "Receive feedback without defending for 24 hours before responding."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Kim Scott. Summary is our own."},
    {"slug": "multipliers", "title": "Multipliers", "author": "Liz Wiseman", "year": "2010",
     "theme": "Amplifying Talent", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "How the best leaders make everyone around them smarter — Multipliers vs. Diminishers.",
     "why_sk": "It exposes how well-meaning smart leaders accidentally shrink their teams.",
     "lessons": ["Multipliers amplify intelligence; Diminishers drain it.", "Ask questions instead of giving answers.",
                 "Give the toughest challenges to stretch people.", "Debate decisions to sharpen thinking.",
                 "Hold people accountable with ownership."],
     "ritual": "Catch your inner Diminisher daily and switch to asking, not telling.",
     "ritual_pro": ["Answer one question with a better question each day.",
                    "Hand a stretch challenge to someone who's ready but untested."],
     "ritual_personal": ["Resist rescuing; let people solve it themselves once a day.",
                        "Ask more than you assert in one conversation daily."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Liz Wiseman. Summary is our own."},
    {"slug": "turn-the-ship-around", "title": "Turn the Ship Around!", "author": "L. David Marquet", "year": "2012",
     "theme": "Empowerment", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "A submarine captain's story of turning followers into leaders by giving control.",
     "why_sk": "The best real-world case for leader-leader, not leader-follower, management.",
     "lessons": ["Give control, don't take it.", "Move authority to where the information is.",
                 "Replace 'permission to' with 'I intend to'.", "Competence and clarity make delegation safe.",
                 "Leaders create leaders, not followers."],
     "ritual": "Push authority down a little every day until 'I intend to' becomes the team's language.",
     "ritual_pro": ["Encourage 'I intend to…' from your team instead of asking permission.",
                    "Delegate one decision to where the information actually lives."],
     "ritual_personal": ["Give family members real control over a shared decision.",
                        "Notice where you hoard control out of habit and release one."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© L. David Marquet. Summary is our own."},
    {"slug": "culture-code", "title": "The Culture Code", "author": "Daniel Coyle", "year": "2018",
     "theme": "Culture", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "The secrets of highly successful groups — how great cultures are actually built.",
     "why_sk": "It makes 'culture' concrete: safety, vulnerability and shared purpose, built by signals.",
     "lessons": ["Build safety with belonging cues.", "Share vulnerability to build trust.",
                 "Establish purpose with clear stories.", "Small signals shape big cultures.",
                 "Culture is a set of living practices, not a poster."],
     "ritual": "Send belonging cues every day — culture is built in tiny, repeated signals.",
     "ritual_pro": ["Send three small belonging cues a day (eye contact, thanks, 'we').",
                    "Admit one mistake openly each week to model vulnerability."],
     "ritual_personal": ["Tell the story of 'why we do this' at home this week.",
                        "Notice and repeat the small signals that make people feel they belong."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Daniel Coyle. Summary is our own."},
    {"slug": "never-split-difference", "title": "Never Split the Difference", "author": "Chris Voss", "year": "2016",
     "theme": "Negotiation", "public_domain": False, "gutenberg": "", "audio": "",
     "blurb": "An FBI hostage negotiator's field-tested tools for high-stakes negotiation.",
     "why_sk": "The most practical negotiation book I recommend — tactical empathy that actually works.",
     "lessons": ["Tactical empathy: label the other side's emotions.", "Get to 'that's right', not 'yes'.",
                 "Use calibrated 'how' and 'what' questions.", "Silence and mirroring do heavy lifting.",
                 "'No' is the start of the negotiation, not the end."],
     "ritual": "Rehearse tactical empathy in low-stakes talks so it's ready for the high-stakes one.",
     "ritual_pro": ["Label the other person's emotion in one conversation daily ('it seems like…').",
                    "Replace a demand with a calibrated 'how am I supposed to do that?'"],
     "ritual_personal": ["Mirror the last three words to keep someone talking at home.",
                        "Aim for 'that's right' in your next disagreement, not agreement to end it."],
     "source": "Buy the book (Amazon) · curated talks on YouTube.",
     "credit": "© Chris Voss. Summary is our own."},
]

BOOKS_BY_SLUG = {b["slug"]: b for b in BOOKS}
