"""Seed content for Sudarshan Karweer thought-leadership platform."""

IMG = {
    "hero": "https://images.unsplash.com/photo-1560250097-0b93528c311a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "meeting": "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "solar": "https://images.unsplash.com/photo-1509391366360-2e959784a276?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "hydrogen": "https://images.unsplash.com/photo-1587127831640-7423ae037873?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "storage": "https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "finance": "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "bus": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "climate": "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "economy": "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "wind": "https://images.unsplash.com/photo-1466611653911-95081537e5b7?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
}

# category: news | blog | analysis | rd | casestudy
ARTICLES = [
    {
        "slug": "india-record-solar-fy26",
        "category": "news",
        "title": "India Adds Record 30+ GW of Solar as the Energy Transition Compounds",
        "summary": "The latest fiscal saw India commission over 30 GW of solar capacity — a signal that the transition is now self-reinforcing across manufacturing, financing and grid integration.",
        "tags": ["Macro", "Solar", "India"],
        "sector": "Renewable Energy",
        "image": IMG["solar"],
        "featured": True,
        "content": "India's clean-energy build-out crossed an inflection point this fiscal, with more than 30 GW of solar capacity commissioned in a single year. What makes the number remarkable is not the headline figure but the compounding effect underneath it: domestic cell and module capacity is scaling under ALMM and DCR protection, project finance is deepening, and grid-connection queues are being cleared faster than at any point in the last decade.\n\nFor business owners in the renewable and storage space, the macro signal is clear — the cost of capital and the cost of delay now move in opposite directions. Projects that reach financial close early capture protected margins; those that wait risk multiple compression as ~65 GW of cell capacity commissions through FY27.\n\nThe strategic takeaway for founders: treat the transition as a capacity-planning problem, not a subsidy-chasing one. Lock supply, structure bankable offtake, and build storage optionality into every new asset.",
    },
    {
        "slug": "rbi-liquidity-msme-credit",
        "category": "news",
        "title": "Macro Watch: Liquidity, Rates and What They Mean for MSME Credit",
        "summary": "A read on the current rate cycle, systemic liquidity and how it reshapes working-capital access for growth-stage businesses.",
        "tags": ["Macro", "Economy", "Credit"],
        "sector": "Economy",
        "image": IMG["economy"],
        "featured": False,
        "content": "Monetary policy is the tide that lifts or strands every balance sheet. As systemic liquidity tightens and lenders re-price risk, growth-stage businesses feel it first in working-capital lines and project debt.\n\nThe micro-economic consequence is a widening gap between businesses that have institutional-grade financial reporting and those that do not. Lenders reward predictability. Founders who can present clean unit economics, sculpted debt schedules and stress-tested cash flows access cheaper capital even in a tight cycle.\n\nThis is where advisory pays for itself many times over — turning an operating story into a credit story that a committee can underwrite.",
    },
    {
        "slug": "bess-cost-curve-2026",
        "category": "analysis",
        "title": "The BESS Cost Curve: Why Storage Economics Just Crossed the Bankability Line",
        "summary": "LFP cell prices, container CAPEX and augmentation planning — a desk view on when standalone storage becomes a financeable asset class in India.",
        "tags": ["BESS", "Storage", "Valuation"],
        "sector": "Energy Storage",
        "image": IMG["storage"],
        "featured": True,
        "content": "Battery energy storage has quietly crossed the line from pilot to portfolio. LFP cell indices near $46/kWh and container CAPEX around $66/kWh have compressed the levelised cost of storage to a point where capacity plus availability revenue stacks now clear lender DSCR thresholds.\n\nThe analytical nuance is duration. Multi-hour systems are sized not by peak MW but by the revenue their MWh can address — ancillary services, ToD arbitrage and firming for RTC/FDRE contracts. The right sizing logic, augmentation plan and degradation curve determine whether a project is bankable or merely buildable.\n\nFor investors and developers: the alpha is no longer in owning storage — it is in structuring it. Contract design, warranty stacking and augmentation reserves separate a 10% IRR from an 18% one.",
    },
    {
        "slug": "green-hydrogen-cost-parity",
        "category": "analysis",
        "title": "Green Hydrogen: Mapping the Path to Cost Parity in Hard-to-Abate Sectors",
        "summary": "Electrolyser CAPEX, renewable power tariffs and offtake certainty — what has to be true for green hydrogen to scale in refining, fertiliser and steel.",
        "tags": ["Green Hydrogen", "Decarbonisation"],
        "sector": "Green Hydrogen",
        "image": IMG["hydrogen"],
        "featured": False,
        "content": "Green hydrogen's economics hinge on three variables: the delivered cost of renewable electricity, electrolyser CAPEX and utilisation. Each is moving in the right direction, but the binding constraint is offtake certainty.\n\nHard-to-abate sectors — refining, ammonia/fertiliser and steel — offer the anchor demand that makes gigawatt-scale electrolysis financeable. The India Green Hydrogen Mission's production incentives narrow the gap, but the decisive lever is long-tenor offtake structured around firm, round-the-clock renewable supply.\n\nOur view: the first bankable projects will be co-located with captive RE and storage, underwritten by creditworthy industrial offtakers, and structured with blended finance to de-risk the early cost curve.",
    },
    {
        "slug": "climate-finance-blended-capital",
        "category": "blog",
        "title": "Blended Finance: The Capital Structure the Energy Transition Actually Needs",
        "summary": "Why concessional capital, guarantees and commercial debt must be layered — not stacked — to move climate projects from viable to bankable.",
        "tags": ["Green Financing", "Climate Finance"],
        "sector": "Green Financing",
        "image": IMG["finance"],
        "featured": True,
        "content": "The climate-financing gap is not a shortage of capital — it is a mismatch of risk appetite and return expectations. Blended finance solves this by layering concessional and commercial capital so each tranche is priced to the risk it can actually bear.\n\nDone well, a first-loss guarantee or a concessional senior tranche can crowd in three to four times its value in commercial debt. Done poorly, it simply subsidises returns that would have happened anyway. The craft is in the structuring — sizing the guarantee to the specific risk that keeps commercial lenders out.\n\nFor founders raising for RE, storage or hydrogen: understand the mandate of every capital provider at the table. Development finance institutions, climate funds and commercial banks are solving different problems. Align your structure to their constraints and the round closes.",
    },
    {
        "slug": "scaling-playbook-founders",
        "category": "blog",
        "title": "The Scaling Playbook: From Founder-Led to System-Led Growth",
        "summary": "Most businesses don't fail from lack of demand — they stall because the operating system can't scale with the founder. Here's how to change that.",
        "tags": ["Strategy", "Scaling", "Coaching"],
        "sector": "Business Strategy",
        "image": IMG["meeting"],
        "featured": False,
        "content": "Every founder hits the ceiling of their own bandwidth. The businesses that break through are the ones that convert founder intuition into repeatable systems — in sales, hiring, capital allocation and decision rights.\n\nAcross 60+ engagements with corporates and CXOs, one pattern repeats: growth stalls not from a weak market but from an operating model that still routes every decision through one person. Scaling is the deliberate act of designing yourself out of the critical path.\n\nThe work is unglamorous — governance cadences, a clean org design, a capital plan tied to milestones, and a leadership team that owns outcomes. But it is what turns a good business into an enduring one.",
    },
    {
        "slug": "climate-change-physical-risk",
        "category": "blog",
        "title": "Pricing Physical Climate Risk into Your Business Strategy",
        "summary": "Heat, water stress and supply-chain disruption are now balance-sheet items. A framework for boards to price climate risk before it prices them.",
        "tags": ["Climate Change", "Sustainability", "Risk"],
        "sector": "Sustainability",
        "image": IMG["climate"],
        "featured": False,
        "content": "Climate risk has graduated from a CSR footnote to a core strategic variable. Physical risks — heat stress, water scarcity, extreme weather — now shape site selection, insurance costs and supply-chain resilience.\n\nBoards that treat climate as a compliance exercise will be repriced by lenders and insurers who have already internalised it. The winners quantify exposure, build adaptation into capital plans, and turn resilience into a competitive moat.\n\nSustainability, done commercially, is not a cost centre. It is a lens that surfaces cost, risk and opportunity a competitor without it simply cannot see.",
    },
    {
        "slug": "solid-state-battery-rd",
        "category": "rd",
        "title": "R&D Watch: Solid-State and Sodium-Ion — The Next Storage Chemistries",
        "summary": "A technology scan of the chemistries competing to succeed LFP — and what their maturity curves mean for asset planning today.",
        "tags": ["R&D", "Battery Tech", "Storage"],
        "sector": "Energy Storage",
        "image": IMG["storage"],
        "featured": False,
        "content": "LFP dominates today, but the R&D frontier is crowded. Solid-state cells promise higher energy density and safety; sodium-ion offers a low-cost, resource-abundant alternative for stationary storage where weight is not the constraint.\n\nFor asset owners, the practical question is timing. Building an augmentation strategy today means underwriting the chemistry roadmap — leaving room to adopt cheaper, denser cells at replacement without stranding the balance-of-plant.\n\nThe R&D signal to watch: cycle-life and calendar-life data at grid scale, not lab-cell headlines. Bankability follows demonstrated durability, not press releases.",
    },
    {
        "slug": "electrolyser-technology-scan",
        "category": "rd",
        "title": "R&D Watch: Alkaline vs PEM vs AEM Electrolysers",
        "summary": "The electrolyser technology landscape decoded — efficiency, CAPEX trajectory and where each chemistry wins as green hydrogen scales.",
        "tags": ["R&D", "Green Hydrogen", "Electrolysers"],
        "sector": "Green Hydrogen",
        "image": IMG["hydrogen"],
        "featured": False,
        "content": "Electrolyser selection is a CAPEX-versus-flexibility trade-off. Alkaline systems are proven and cheap but respond slowly; PEM handles variable renewable input elegantly at a cost premium; AEM promises to combine the best of both but is earlier on the maturity curve.\n\nFor projects co-located with variable solar and wind, response time and turndown ratio matter as much as sticker efficiency. The right choice depends on the power profile and the offtake contract, not on which technology has the best datasheet.\n\nOur R&D desk tracks stack-cost trajectories and degradation data to help clients avoid locking into a chemistry that a two-year roadmap will render uncompetitive.",
    },
    {
        "slug": "msrtc-bus-depot-monetisation",
        "category": "casestudy",
        "title": "Monetising Government Assets: The MSRTC Bus Depot Blueprint",
        "summary": "How under-utilised state transport land — bus depots across Maharashtra — can be unlocked into commercial value without disrupting core operations.",
        "tags": ["Asset Monetisation", "Government", "Infrastructure"],
        "sector": "Asset Monetisation",
        "image": IMG["bus"],
        "featured": True,
        "content": "State transport undertakings sit on some of the most valuable, best-located and most under-monetised real estate in India. The MSRTC bus depot monetisation programme reframed these depots not as cost centres but as mixed-use assets — commercial development layered above continued transport operations.\n\nThe engagement structured a model that preserved public-service continuity while unlocking commercial value: air-rights development, retail and commercial leasing, and long-tenor concession structures that transfer development risk to private partners while retaining public ownership of the land.\n\nThe result is a replicable blueprint — a monetisation framework that converts a recurring fiscal drain into a self-funding, revenue-generating asset base, applicable across transport, land and infrastructure portfolios of state and central undertakings.",
    },
    {
        "slug": "utility-scale-bess-financial-close",
        "category": "casestudy",
        "title": "From Concept to Financial Close: A 120 MW / 480 MWh Storage Mandate",
        "summary": "Structuring the advisory, engineering and capital stack that took a standalone BESS project from a whiteboard to a bankable, financed asset.",
        "tags": ["BESS", "Advisory", "Project Finance"],
        "sector": "Energy Storage",
        "image": IMG["storage"],
        "featured": False,
        "content": "A standalone battery storage project lives or dies on the coherence of its revenue stack. This 120 MW / 480 MWh mandate required aligning technical sizing, contract structure and debt design into a single bankable thesis.\n\nThe work spanned four-hour LFP system engineering, augmentation and degradation planning, a value-engineering exercise that cut CAPEX materially, and a financing structure that survived credit-committee scrutiny on DSCR and IRR.\n\nThe outcome: a financed, buildable asset — and a template for turning storage ambition into storage infrastructure.",
    },
    {
        "slug": "fundraising-narrative-energy",
        "category": "blog",
        "title": "Fundraising in Energy: Building a Narrative Institutional Capital Believes",
        "summary": "Why the best energy raises are won on the quality of the risk story, not the size of the market — and how founders can reframe theirs.",
        "tags": ["Fundraising", "Strategy", "Energy"],
        "sector": "Business Strategy",
        "image": IMG["finance"],
        "featured": False,
        "content": "Institutional capital does not buy market size — it buys de-risked execution. The energy founders who raise well are those who convert a technology or market story into a risk story an investment committee can underwrite line by line.\n\nThat means being brutally clear about the three risks that matter — offtake, execution and financing — and showing how each is contracted, hedged or structured away. A raise stalls not because the vision is unclear but because the risk map is.\n\nHaving sat on both sides of the table across 60+ projects, the pattern is consistent: the sharpest narrative, backed by lender-grade numbers, wins the term sheet.",
    },
]

SERVICES = [
    {
        "no": "01",
        "title": "Premium 1:1 Strategic Consultation",
        "desc": "Direct advisory for business owners in renewable energy and storage — strategy, fundraising, new business development and scaling. High-signal, decision-grade counsel.",
        "tags": ["Strategy", "Fundraising", "Scaling"],
        "image": IMG["meeting"],
    },
    {
        "no": "02",
        "title": "RE, Storage & Green Hydrogen Advisory",
        "desc": "End-to-end advisory across renewables, BESS and green hydrogen — feasibility, technology selection, bankability and offtake structuring.",
        "tags": ["Renewables", "BESS", "Hydrogen"],
        "image": IMG["solar"],
    },
    {
        "no": "03",
        "title": "Green & Climate Financing",
        "desc": "Blended finance, sustainability-linked structures and debt syndication that move climate projects from viable to financially closed.",
        "tags": ["Blended Finance", "Debt", "Climate"],
        "image": IMG["finance"],
    },
    {
        "no": "04",
        "title": "Government Asset Monetisation",
        "desc": "Unlocking value from public assets — from MSRTC bus depots to land and infrastructure portfolios — with structures that preserve public interest.",
        "tags": ["Monetisation", "Infrastructure", "PPP"],
        "image": IMG["bus"],
    },
    {
        "no": "05",
        "title": "Business Coaching for Founders & CXOs",
        "desc": "23+ years distilled into a coaching engagement that turns founder-led hustle into system-led, scalable growth.",
        "tags": ["Coaching", "Leadership", "Growth"],
        "image": IMG["economy"],
    },
]

STATS = [
    {"value": "23+", "label": "Years of Experience"},
    {"value": "60+", "label": "Projects Delivered"},
    {"value": "CXO", "label": "Corporate Advisory"},
    {"value": "4", "label": "Sectors of Depth"},
]

MARKET_PULSE = [
    {"name": "GFY LFP Cell Index", "value": "$46.15/kWh", "change": "+0.4%", "up": True},
    {"name": "BESS Container (CN)", "value": "$65.84/kWh", "change": "-0.8%", "up": False},
    {"name": "Lithium Carbonate", "value": "¥1,59,600/MT", "change": "+4.77%", "up": True},
    {"name": "Copper LME", "value": "$9,404/MT", "change": "0.0%", "up": True},
    {"name": "Solar Modules (India)", "value": "₹18.5/Wp", "change": "-1.2%", "up": False},
    {"name": "Green H₂ (levelised)", "value": "$4.10/kg", "change": "-2.1%", "up": False},
]

TESTIMONIALS = [
    {
        "quote": "Sudarshan reframed our entire fundraising narrative. We closed our round in half the time we expected.",
        "name": "Founder & CEO",
        "role": "Renewable Energy Developer",
    },
    {
        "quote": "The clarity he brings on storage economics and bankability is rare. He thinks like an engineer and a financier at once.",
        "name": "Managing Director",
        "role": "Energy Storage Company",
    },
    {
        "quote": "His asset-monetisation framework unlocked value we had written off as dormant. A genuine strategic partner.",
        "name": "Senior Official",
        "role": "State Transport Undertaking",
    },
]
