"""Structured service definitions with workflows, approach and outcomes."""

IMG = {
    "solar": "https://images.unsplash.com/photo-1509391366360-2e959784a276?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "storage": "https://images.unsplash.com/photo-1589276534126-adef63a95e05?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "finance": "https://images.unsplash.com/photo-1675116731363-c17d957f3444?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "bus": "https://images.unsplash.com/photo-1572675339312-3e8b094a544d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "coaching": "https://images.unsplash.com/photo-1573166364839-1bfe9196c23e?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "strategy": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
}

# portrait keys map to processed images set on the frontend
SERVICES = [
    {
        "slug": "business-strategy",
        "portrait": "advisory",
        "signature": True,
        "title": "Business & Growth Strategy",
        "tagline": "The rigour of a top-tier strategy house, with an owner's bias for action.",
        "hero_image": IMG["strategy"],
        "overview": "Board-grade strategy across the full arc — market entry, feasibility, growth and portfolio optimisation — delivered with the structured problem-solving you'd expect from McKinsey, BCG or Bain, and the execution focus of an operator who has actually built and scaled businesses. Every engagement comes with the frameworks and toolkit to keep the thinking alive after the deck is closed.",
        "workflow": [
            {"key": "entry", "title": "Market Entry", "summary": "Enter the right market, the right way, without bleeding.",
             "detail": "We size the real prize before you fall in love with it — addressable demand, regulatory pathway, cost-to-serve and the competitive response. Then we pick the entry mode (build, partner, JV or acquire) on purpose, and design a defensible beachhead you can expand from.",
             "steps": ["Opportunity sizing & regulatory pathway", "Entry-mode decision (build / partner / JV / acquire)", "Beachhead segment & go-to-market", "Pre-committed expand / exit triggers"]},
            {"key": "feasibility", "title": "Feasibility", "summary": "Prove it works on paper before it costs you in the field.",
             "detail": "A hard-nosed feasibility read across commercial, technical, financial and risk dimensions. If the model only works on best-case assumptions, we find that out now — with a structured issue tree and root-cause discipline, not optimism.",
             "steps": ["Commercial & technical feasibility", "Unit economics & sensitivity analysis", "Risk map and root-cause (5 Whys / Fishbone)", "Go / no-go with explicit assumptions"]},
            {"key": "growth", "title": "Growth", "summary": "Growth that compounds — profitable, defensible, repeatable.",
             "detail": "We separate vanity growth from value-creating growth using the Ansoff logic, sequence the bets so each stage funds the next, and translate them into a 90-day operating cadence with owners, metrics and milestones.",
             "steps": ["Growth-vector prioritisation (Ansoff)", "Moat & advantage design (VRIO / Value Chain)", "90-day operating cadence", "Metric & milestone architecture"]},
            {"key": "portfolio", "title": "Portfolio Optimisation", "summary": "Fund the winners, fix or exit the rest.",
             "detail": "Disciplined capital allocation across the portfolio using BCG growth-share logic and a balanced scorecard — redirect cash from cows to stars, set explicit decisions on the dogs, and balance the book so today's cash funds tomorrow's growth.",
             "steps": ["Portfolio mapping (BCG)", "Capital reallocation plan", "Fix / hold / divest decisions", "Balanced-scorecard performance system"]},
        ],
        "approach": [
            "Structured, MECE problem-solving — issue trees, hypotheses and root-cause rigour, not opinion.",
            "Operator's lens: every recommendation is mapped to a decision, a metric and a 90-day move.",
            "You keep the frameworks — a full strategy toolkit and operational guidelines travel with the engagement.",
        ],
        "outcomes": [
            "A sharp, evidence-based strategy your board and investors can underwrite.",
            "A prioritised, sequenced growth agenda with clear owners and milestones.",
            "A rebalanced portfolio and capital plan that funds the winners.",
        ],
    },
    {
        "slug": "ma-advisory",
        "portrait": "hero",
        "signature": True,
        "title": "M&A Advisory",
        "tagline": "Sudarshan's signature strength — deals won after signing, not just at the table.",
        "hero_image": IMG["finance"],
        "proof": [
            {"value": "$2B+", "label": "Transaction value advised"},
            {"value": "15+", "label": "Buy & sell-side deals"},
            {"value": "Loyalty", "label": "Airline programme carve-outs"},
            {"value": "6", "label": "Sectors covered"},
        ],
        "overview": "End-to-end M&A advisory — thesis, target screening, valuation, diligence, structuring and the integration that actually captures value. Sudarshan brings hands-on deal experience across sectors, including complex carve-outs such as airline loyalty programmes — where a frequent-flyer business is separated, valued and monetised as a standalone asset. Most deals destroy value in integration; these are built to create it.",
        "workflow": [
            {"key": "thesis", "title": "Thesis & Screening", "summary": "Buy a capability, not a logo.",
             "detail": "We define what the deal must achieve strategically and screen targets against it — running VRIO on each so you're paying for something valuable, rare and hard to build, not a premium for parity.",
             "steps": ["Deal thesis & strategic rationale", "Target screening & prioritisation", "Capability & VRIO assessment", "Preliminary value hypothesis"]},
            {"key": "diligence", "title": "Valuation & Diligence", "summary": "Price the synergies you can actually capture.",
             "detail": "Rigorous valuation and commercial, financial and operational diligence — separating real cost synergies from hopeful revenue synergies, stress-testing the model, and surfacing the risks that should shape price and terms.",
             "steps": ["Valuation & synergy modelling", "Commercial & operational diligence", "Risk identification & mitigation", "Negotiation support"]},
            {"key": "carveout", "title": "Structuring & Carve-Out", "summary": "Separate and value the asset cleanly.",
             "detail": "Deal and entity structuring, including carve-outs — for example, separating an airline loyalty / frequent-flyer programme into a standalone, financeable business. We design the perimeter, the transitional arrangements and the standalone operating model.",
             "steps": ["Deal & entity structuring", "Carve-out perimeter & TSAs", "Standalone operating model", "Tax & regulatory alignment"]},
            {"key": "integration", "title": "Integration", "summary": "Where the value is actually created.",
             "detail": "A 100-day integration plan formed before signing — the operating model, key-people retention, systems and culture (7S alignment) — plus a clear view of what to integrate and what to deliberately keep separate.",
             "steps": ["100-day integration plan", "Key-talent retention", "7S alignment & culture", "Synergy capture tracking"]},
        ],
        "approach": [
            "Practical, deal-tested experience — including airline loyalty and frequent-flyer carve-outs and monetisation.",
            "Synergy discipline: real cost synergies underwritten, revenue synergies haircut honestly.",
            "Integration designed in diligence, so value is captured in the first quarter — not lost in it.",
        ],
        "outcomes": [
            "A disciplined deal thesis and a target you're buying for the right reasons.",
            "A defensible valuation and terms that reflect real, capturable synergies.",
            "A carve-out or integration plan that protects what made the asset valuable.",
        ],
    },
    {
        "slug": "fund-raising",
        "portrait": "advisory",
        "signature": True,
        "title": "Fund Raising & Capital",
        "tagline": "Over $3 billion raised — capital strategy from an operator who has closed the rounds.",
        "hero_image": IMG["finance"],
        "proof": [
            {"value": "$3B+", "label": "Capital raised & closed"},
            {"value": "Equity·Debt·Blended", "label": "Instruments structured"},
            {"value": "Project→Corporate", "label": "Across funding stages"},
            {"value": "Multi-sector", "label": "Energy, infra & industrials"},
        ],
        "overview": "Capital-raising advisory across equity, debt and blended finance — from readiness and narrative to structuring, investor engagement and close. Sudarshan has led and supported fund-raises totalling over $3 billion successfully completed, spanning project, growth and corporate capital. Capital follows credibility; we do the work that gets you funded in the quarters before the raise, not the week of it.",
        "workflow": [
            {"key": "readiness", "title": "Capital Readiness", "summary": "Be bankable before you fundraise.",
             "detail": "We systematically retire the risks a lender or investor will price — offtake, execution, technology, counterparty and cash-flow certainty — and build a clean, complete data room that answers questions before they're asked.",
             "steps": ["Risk de-risking programme", "Financial model & cash-flow certainty", "Investor-grade data room", "Valuation & ask calibration"]},
            {"key": "narrative", "title": "Narrative & Structure", "summary": "Connect the wedge to the cash flows.",
             "detail": "A fundraising narrative investors underwrite — tying a sharp strategic wedge to the returns it produces — and a capital structure that optimises cost of capital and control across equity, debt and blended or concessional sources.",
             "steps": ["Investment narrative & materials", "Capital structuring (equity / debt / blended)", "Cost-of-capital & control optimisation", "Term-sheet strategy"]},
            {"key": "engagement", "title": "Investor Engagement", "summary": "The right rooms, the right sequence.",
             "detail": "Targeted investor and lender mapping, outreach sequencing and process management — running a disciplined process that creates tension and protects your terms, drawing on relationships across strategic, financial and development-finance capital.",
             "steps": ["Investor / lender targeting", "Outreach & process management", "Due-diligence coordination", "Momentum & competitive tension"]},
            {"key": "close", "title": "Structure & Close", "summary": "From term sheet to money in the bank.",
             "detail": "Negotiation support, documentation coordination and close management — holding the line on the terms that matter and getting the round over the line cleanly.",
             "steps": ["Negotiation & terms", "Documentation coordination", "Conditions-precedent management", "Close & post-close setup"]},
        ],
        "approach": [
            "Track record: 3B+ USD in capital raised and closed across project, growth and corporate finance.",
            "Bankability-first — risks retired and the data room built before investors ever see the deck.",
            "Structure as leverage: the right blend of equity, debt and concessional capital, engineered for cost and control.",
        ],
        "outcomes": [
            "A de-risked, investor-ready business and a data room that builds confidence.",
            "A capital structure engineered for the lowest viable cost and the control you need.",
            "A well-run process that closes on terms you can live with.",
        ],
    },
    {
        "slug": "premium-consultation",
        "portrait": "advisory",
        "title": "Premium 1:1 Strategic Consultation",
        "tagline": "Decision-grade counsel, one conversation at a time.",
        "hero_image": IMG["strategy"],
        "overview": "A focused, high-signal engagement for business owners in renewable energy and storage — and founders who need a sharper edge on strategy, fundraising, new business development and scaling. You bring the decision; Sudarshan brings 23+ years and 60+ projects of pattern recognition to make it a better one.",
        "workflow": [
            {"key": "discovery", "title": "Discovery & Framing", "summary": "We define the real question behind the question.",
             "detail": "Most stuck decisions are stuck because the wrong question is being asked. We start by reframing the problem in terms of the decision to be made, the constraints that actually bind, and the outcome that would count as success.",
             "steps": ["Pre-read of your context & numbers", "Problem reframing session", "Explicit decision & success criteria"]},
            {"key": "diagnosis", "title": "Diagnosis", "summary": "A candid read of what's working and what's in the way.",
             "detail": "We stress-test the current strategy, unit economics and go-to-market against how capital, customers and regulators actually behave — and surface the two or three things that matter most.",
             "steps": ["Strategy & unit-economics review", "Risk map: offtake, execution, financing", "Prioritised list of what moves the needle"]},
            {"key": "roadmap", "title": "Roadmap", "summary": "A sequenced, owner-ready action plan.",
             "detail": "You leave with a concrete, sequenced plan — what to do next, in what order, and how to tell if it's working — mapped to milestones an investor or board would recognise.",
             "steps": ["90-day action sequence", "Milestone & metric design", "Capital / hiring / GTM priorities"]},
            {"key": "followup", "title": "Follow-Through", "summary": "Accountability so the plan actually happens.",
             "detail": "Strategy dies in the gap between the meeting and Monday. Follow-up access keeps momentum, adjusts the plan to reality, and holds the line on the decisions that matter.",
             "steps": ["Written session notes", "Priority follow-up access", "Checkpoint on progress"]},
        ],
        "approach": [
            "Engineer-plus-financier lens: recommendations grounded in how assets and capital really behave.",
            "Radical candour over comfortable consensus — you get the read you can't get internally.",
            "Everything mapped to a decision and a metric, never abstract advice.",
        ],
        "outcomes": [
            "A clear, sequenced plan for your next 90 days.",
            "A sharper fundraising or growth narrative investors underwrite.",
            "Confidence on the one or two decisions that actually move the business.",
        ],
    },
    {
        "slug": "re-storage-hydrogen",
        "portrait": "hero",
        "title": "RE, Storage & Green Hydrogen Advisory",
        "tagline": "From concept to bankable, buildable asset.",
        "hero_image": IMG["storage"],
        "overview": "End-to-end advisory across renewables, battery energy storage (BESS) and green hydrogen — feasibility, technology selection, sizing, bankability and offtake structuring. We sit at the intersection of engineering and capital so your project survives both an engineer's and a lender's scrutiny.",
        "workflow": [
            {"key": "assess", "title": "Assess", "summary": "Resource, site, grid and regulatory scan.",
             "detail": "We size the opportunity honestly — resource quality, grid availability, regulatory pathway and the commercial envelope — before a rupee is committed.",
             "steps": ["Resource & site assessment", "Grid & regulatory scan", "Opportunity & risk sizing"]},
            {"key": "engineer", "title": "Engineer", "summary": "Right-sized technical design.",
             "detail": "Technology selection and system sizing for solar, wind, hybrid, BESS or electrolysers — matched to the power profile and the offtake contract, not to a datasheet.",
             "steps": ["Technology selection", "BESS / electrolyser sizing", "Degradation & augmentation plan"]},
            {"key": "structure", "title": "Structure", "summary": "Offtake and revenue-stack design.",
             "detail": "We structure the offtake and revenue stack — RTC/FDRE firming, ancillary services, ToD arbitrage — so the asset is not just buildable but bankable.",
             "steps": ["Offtake & PPA structuring", "Revenue-stack modelling", "Bankability positioning"]},
            {"key": "diligence", "title": "Diligence & Close", "summary": "Lender-grade due diligence support.",
             "detail": "Technical and financial due diligence, DPR/TEV support and independent-engineer positioning to carry the project through credit committee to financial close.",
             "steps": ["Technical & financial DD", "DPR / TEV support", "Path to financial close"]},
        ],
        "approach": [
            "First-principles engineering behind every commercial recommendation.",
            "Duration and offtake, not nameplate MW, drive our sizing logic.",
            "Bankability designed in from day one, not retrofitted before close.",
        ],
        "outcomes": [
            "A technically sound, right-sized project configuration.",
            "A revenue stack and offtake structure lenders will fund.",
            "A credible, de-risked path from concept to financial close.",
        ],
    },
    {
        "slug": "green-climate-financing",
        "portrait": "coaching",
        "title": "Green & Climate Financing",
        "tagline": "Turning robust projects into financial close.",
        "hero_image": IMG["finance"],
        "overview": "Sustainability-linked structures, blended finance and debt syndication that move climate projects from viable to financially closed. The climate-financing gap is a mismatch of risk appetite and return expectation — we structure capital so each tranche is priced to the risk it can bear.",
        "workflow": [
            {"key": "model", "title": "Model", "summary": "Lender-grade financial modelling.",
             "detail": "A fully linked, scenario-ready model — debt sculpting, DSCR, IRR, sensitivities — built the way credit committees actually read them.",
             "steps": ["15–25 year cash-flow engine", "Debt sculpting & DSCR", "Sensitivity & risk analysis"]},
            {"key": "structure", "title": "Structure", "summary": "The right capital stack.",
             "detail": "We layer concessional, blended and commercial capital, and design sustainability-linked or green frameworks that crowd in commercial lenders efficiently.",
             "steps": ["Blended-finance design", "Green / SLL frameworks", "First-loss & guarantee sizing"]},
            {"key": "syndicate", "title": "Syndicate", "summary": "Match the mandate to the money.",
             "detail": "We take the structure to the right lenders — DFIs, climate funds, banks — aligned to each provider's mandate and constraints, and drive term sheets to close.",
             "steps": ["Lender mapping & outreach", "Term-sheet negotiation", "Financial close"]},
        ],
        "approach": [
            "Every structure sized to the specific risk that keeps commercial lenders out.",
            "We speak the language of DFIs, climate funds and commercial banks alike.",
            "Numbers built to survive scrutiny, not to look good in a deck.",
        ],
        "outcomes": [
            "A bankable capital structure with the right blend of capital.",
            "Term sheets from lenders whose mandate fits your project.",
            "A shorter, more certain path to financial close.",
        ],
    },
    {
        "slug": "asset-monetisation",
        "portrait": "advisory",
        "title": "Government Asset Monetisation",
        "tagline": "Unlocking dormant public value — responsibly.",
        "hero_image": IMG["bus"],
        "overview": "Unlocking value from under-utilised public assets — from MSRTC bus depots to land and infrastructure portfolios — with structures that preserve public interest and service continuity. A recurring fiscal drain becomes a self-funding, revenue-generating asset base.",
        "workflow": [
            {"key": "audit", "title": "Asset Audit", "summary": "Map the portfolio and its latent value.",
             "detail": "We inventory the assets, their locations and encumbrances, and identify where the latent commercial value actually sits without disrupting core operations.",
             "steps": ["Portfolio inventory", "Highest-and-best-use analysis", "Encumbrance & title review"]},
            {"key": "structure", "title": "Structuring", "summary": "Models that protect the public interest.",
             "detail": "Air-rights development, commercial leasing and long-tenor concessions — structured to transfer development risk to private partners while public ownership of the land is retained.",
             "steps": ["Monetisation model design", "Concession / PPP structuring", "Public-interest safeguards"]},
            {"key": "execute", "title": "Execution", "summary": "From framework to transaction.",
             "detail": "We take the model to market — bid design, partner selection and transaction management — and stand up a replicable blueprint across the wider portfolio.",
             "steps": ["Bid & transaction design", "Partner selection", "Replicable rollout blueprint"]},
        ],
        "approach": [
            "Continuity first: core public service is never disrupted.",
            "Ownership retained, development risk transferred.",
            "One proven deal becomes a template for the whole portfolio.",
        ],
        "outcomes": [
            "A dormant asset turned into a recurring revenue stream.",
            "Development risk transferred while public ownership is preserved.",
            "A replicable monetisation blueprint across the portfolio.",
        ],
    },
    {
        "slug": "business-coaching",
        "portrait": "coaching",
        "title": "Business Coaching for Founders & CXOs",
        "tagline": "From founder-led hustle to system-led scale.",
        "hero_image": IMG["coaching"],
        "overview": "23+ years distilled into a coaching engagement that turns founder intuition into repeatable systems — in sales, hiring, capital allocation and decision rights. Most businesses stall not from weak demand but from an operating model that still routes every decision through one person.",
        "workflow": [
            {"key": "baseline", "title": "Baseline", "summary": "Where you and the business really are.",
             "detail": "An honest baseline of the business, the leadership team and the founder's own bandwidth — the true constraint on the next stage of growth.",
             "steps": ["Business & org diagnostic", "Leadership & bandwidth review", "Growth-ceiling identification"]},
            {"key": "design", "title": "System Design", "summary": "Design yourself out of the critical path.",
             "detail": "We design the operating system — governance cadences, org and decision rights, and a capital plan tied to milestones — so growth no longer depends on the founder alone.",
             "steps": ["Operating cadence & governance", "Org & decision-rights design", "Milestone-linked capital plan"]},
            {"key": "coach", "title": "Coaching Cadence", "summary": "Sustained accountability and adjustment.",
             "detail": "A regular coaching cadence that installs the systems, coaches the leadership team to own outcomes, and adjusts the plan as the business changes.",
             "steps": ["Regular 1:1 coaching", "Leadership-team enablement", "Quarterly recalibration"]},
        ],
        "approach": [
            "Coach the operating system, not just the operator.",
            "Convert intuition into systems the team can run without you.",
            "Accountability that closes the gap between plan and execution.",
        ],
        "outcomes": [
            "A leadership team that owns outcomes independently.",
            "Repeatable systems in sales, hiring and capital allocation.",
            "A business that scales beyond the founder's bandwidth.",
        ],
    },
]
