"""Structured service definitions with workflows, approach and outcomes."""

IMG = {
    "solar": "https://images.unsplash.com/photo-1509391366360-2e959784a276?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "storage": "https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "finance": "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "bus": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "coaching": "https://images.unsplash.com/photo-1552664730-d307ca884978?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "strategy": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
}

# portrait keys map to processed images set on the frontend
SERVICES = [
    {
        "slug": "premium-consultation",
        "portrait": "advisory",
        "title": "Premium 1:1 Strategic Consultation",
        "tagline": "Decision-grade counsel, one conversation at a time.",
        "hero_image": IMG["strategy"],
        "overview": "A focused, high-signal engagement for business owners in renewable energy and storage — and founders who need a sharper edge on strategy, fundraising, new business development and scaling. You bring the decision; Sudarshan brings 23+ years and 60+ projects of pattern recognition to make it a better one.",
        "workflow": [
            {"key": "discovery", "title": "Discovery & Framing", "summary": "We define the real question behind the question.",
             "detail": "Most stuck decisions are stuck because the wrong question is being asked. We start by reframing the problem in terms of the decision to be made, the constraints that actually bind, and the outcome that would count as success.",
             "steps": ["Pre-read of your context & numbers", "Problem reframing session", "Explicit decision & success criteria"]},
            {"key": "diagnosis", "title": "Diagnosis", "summary": "A candid read of what's working and what's in the way.",
             "detail": "We stress-test the current strategy, unit economics and go-to-market against how capital, customers and regulators actually behave — and surface the two or three things that matter most.",
             "steps": ["Strategy & unit-economics review", "Risk map: offtake, execution, financing", "Prioritised list of what moves the needle"]},
            {"key": "roadmap", "title": "Roadmap", "summary": "A sequenced, owner-ready action plan.",
             "detail": "You leave with a concrete, sequenced plan — what to do next, in what order, and how to tell if it's working — mapped to milestones an investor or board would recognise.",
             "steps": ["90-day action sequence", "Milestone & metric design", "Capital / hiring / GTM priorities"]},
            {"key": "followup", "title": "Follow-Through", "summary": "Accountability so the plan actually happens.",
             "detail": "Strategy dies in the gap between the meeting and Monday. Follow-up access keeps momentum, adjusts the plan to reality, and holds the line on the decisions that matter.",
             "steps": ["Written session notes", "Priority follow-up access", "Checkpoint on progress"]},
        ],
        "approach": [
            "Engineer-plus-financier lens: recommendations grounded in how assets and capital really behave.",
            "Radical candour over comfortable consensus — you get the read you can't get internally.",
            "Everything mapped to a decision and a metric, never abstract advice.",
        ],
        "outcomes": [
            "A clear, sequenced plan for your next 90 days.",
            "A sharper fundraising or growth narrative investors underwrite.",
            "Confidence on the one or two decisions that actually move the business.",
        ],
    },
    {
        "slug": "re-storage-hydrogen",
        "portrait": "hero",
        "title": "RE, Storage & Green Hydrogen Advisory",
        "tagline": "From concept to bankable, buildable asset.",
        "hero_image": IMG["storage"],
        "overview": "End-to-end advisory across renewables, battery energy storage (BESS) and green hydrogen — feasibility, technology selection, sizing, bankability and offtake structuring. We sit at the intersection of engineering and capital so your project survives both an engineer's and a lender's scrutiny.",
        "workflow": [
            {"key": "assess", "title": "Assess", "summary": "Resource, site, grid and regulatory scan.",
             "detail": "We size the opportunity honestly — resource quality, grid availability, regulatory pathway and the commercial envelope — before a rupee is committed.",
             "steps": ["Resource & site assessment", "Grid & regulatory scan", "Opportunity & risk sizing"]},
            {"key": "engineer", "title": "Engineer", "summary": "Right-sized technical design.",
             "detail": "Technology selection and system sizing for solar, wind, hybrid, BESS or electrolysers — matched to the power profile and the offtake contract, not to a datasheet.",
             "steps": ["Technology selection", "BESS / electrolyser sizing", "Degradation & augmentation plan"]},
            {"key": "structure", "title": "Structure", "summary": "Offtake and revenue-stack design.",
             "detail": "We structure the offtake and revenue stack — RTC/FDRE firming, ancillary services, ToD arbitrage — so the asset is not just buildable but bankable.",
             "steps": ["Offtake & PPA structuring", "Revenue-stack modelling", "Bankability positioning"]},
            {"key": "diligence", "title": "Diligence & Close", "summary": "Lender-grade due diligence support.",
             "detail": "Technical and financial due diligence, DPR/TEV support and independent-engineer positioning to carry the project through credit committee to financial close.",
             "steps": ["Technical & financial DD", "DPR / TEV support", "Path to financial close"]},
        ],
        "approach": [
            "First-principles engineering behind every commercial recommendation.",
            "Duration and offtake, not nameplate MW, drive our sizing logic.",
            "Bankability designed in from day one, not retrofitted before close.",
        ],
        "outcomes": [
            "A technically sound, right-sized project configuration.",
            "A revenue stack and offtake structure lenders will fund.",
            "A credible, de-risked path from concept to financial close.",
        ],
    },
    {
        "slug": "green-climate-financing",
        "portrait": "coaching",
        "title": "Green & Climate Financing",
        "tagline": "Turning robust projects into financial close.",
        "hero_image": IMG["finance"],
        "overview": "Sustainability-linked structures, blended finance and debt syndication that move climate projects from viable to financially closed. The climate-financing gap is a mismatch of risk appetite and return expectation — we structure capital so each tranche is priced to the risk it can bear.",
        "workflow": [
            {"key": "model", "title": "Model", "summary": "Lender-grade financial modelling.",
             "detail": "A fully linked, scenario-ready model — debt sculpting, DSCR, IRR, sensitivities — built the way credit committees actually read them.",
             "steps": ["15–25 year cash-flow engine", "Debt sculpting & DSCR", "Sensitivity & risk analysis"]},
            {"key": "structure", "title": "Structure", "summary": "The right capital stack.",
             "detail": "We layer concessional, blended and commercial capital, and design sustainability-linked or green frameworks that crowd in commercial lenders efficiently.",
             "steps": ["Blended-finance design", "Green / SLL frameworks", "First-loss & guarantee sizing"]},
            {"key": "syndicate", "title": "Syndicate", "summary": "Match the mandate to the money.",
             "detail": "We take the structure to the right lenders — DFIs, climate funds, banks — aligned to each provider's mandate and constraints, and drive term sheets to close.",
             "steps": ["Lender mapping & outreach", "Term-sheet negotiation", "Financial close"]},
        ],
        "approach": [
            "Every structure sized to the specific risk that keeps commercial lenders out.",
            "We speak the language of DFIs, climate funds and commercial banks alike.",
            "Numbers built to survive scrutiny, not to look good in a deck.",
        ],
        "outcomes": [
            "A bankable capital structure with the right blend of capital.",
            "Term sheets from lenders whose mandate fits your project.",
            "A shorter, more certain path to financial close.",
        ],
    },
    {
        "slug": "asset-monetisation",
        "portrait": "advisory",
        "title": "Government Asset Monetisation",
        "tagline": "Unlocking dormant public value — responsibly.",
        "hero_image": IMG["bus"],
        "overview": "Unlocking value from under-utilised public assets — from MSRTC bus depots to land and infrastructure portfolios — with structures that preserve public interest and service continuity. A recurring fiscal drain becomes a self-funding, revenue-generating asset base.",
        "workflow": [
            {"key": "audit", "title": "Asset Audit", "summary": "Map the portfolio and its latent value.",
             "detail": "We inventory the assets, their locations and encumbrances, and identify where the latent commercial value actually sits without disrupting core operations.",
             "steps": ["Portfolio inventory", "Highest-and-best-use analysis", "Encumbrance & title review"]},
            {"key": "structure", "title": "Structuring", "summary": "Models that protect the public interest.",
             "detail": "Air-rights development, commercial leasing and long-tenor concessions — structured to transfer development risk to private partners while public ownership of the land is retained.",
             "steps": ["Monetisation model design", "Concession / PPP structuring", "Public-interest safeguards"]},
            {"key": "execute", "title": "Execution", "summary": "From framework to transaction.",
             "detail": "We take the model to market — bid design, partner selection and transaction management — and stand up a replicable blueprint across the wider portfolio.",
             "steps": ["Bid & transaction design", "Partner selection", "Replicable rollout blueprint"]},
        ],
        "approach": [
            "Continuity first: core public service is never disrupted.",
            "Ownership retained, development risk transferred.",
            "One proven deal becomes a template for the whole portfolio.",
        ],
        "outcomes": [
            "A dormant asset turned into a recurring revenue stream.",
            "Development risk transferred while public ownership is preserved.",
            "A replicable monetisation blueprint across the portfolio.",
        ],
    },
    {
        "slug": "business-coaching",
        "portrait": "coaching",
        "title": "Business Coaching for Founders & CXOs",
        "tagline": "From founder-led hustle to system-led scale.",
        "hero_image": IMG["coaching"],
        "overview": "23+ years distilled into a coaching engagement that turns founder intuition into repeatable systems — in sales, hiring, capital allocation and decision rights. Most businesses stall not from weak demand but from an operating model that still routes every decision through one person.",
        "workflow": [
            {"key": "baseline", "title": "Baseline", "summary": "Where you and the business really are.",
             "detail": "An honest baseline of the business, the leadership team and the founder's own bandwidth — the true constraint on the next stage of growth.",
             "steps": ["Business & org diagnostic", "Leadership & bandwidth review", "Growth-ceiling identification"]},
            {"key": "design", "title": "System Design", "summary": "Design yourself out of the critical path.",
             "detail": "We design the operating system — governance cadences, org and decision rights, and a capital plan tied to milestones — so growth no longer depends on the founder alone.",
             "steps": ["Operating cadence & governance", "Org & decision-rights design", "Milestone-linked capital plan"]},
            {"key": "coach", "title": "Coaching Cadence", "summary": "Sustained accountability and adjustment.",
             "detail": "A regular coaching cadence that installs the systems, coaches the leadership team to own outcomes, and adjusts the plan as the business changes.",
             "steps": ["Regular 1:1 coaching", "Leadership-team enablement", "Quarterly recalibration"]},
        ],
        "approach": [
            "Coach the operating system, not just the operator.",
            "Convert intuition into systems the team can run without you.",
            "Accountability that closes the gap between plan and execution.",
        ],
        "outcomes": [
            "A leadership team that owns outcomes independently.",
            "Repeatable systems in sales, hiring and capital allocation.",
            "A business that scales beyond the founder's bandwidth.",
        ],
    },
]
