"""Curated strategy toolkit — each tool renders to a branded PDF worksheet + operational guidelines."""

STRATEGY_TOOLS = [
    {
        "slug": "ansoff-matrix", "name": "Ansoff Growth Matrix", "category": "Growth",
        "tagline": "Choose your next growth move with eyes open on risk.",
        "what_it_is": "A 2x2 that maps four growth paths against how much new risk each carries — by pairing existing vs. new products with existing vs. new markets. It forces an honest conversation about where growth will actually come from.",
        "grid": {"type": "2x2", "x_label": "Products →  Existing / New", "y_label": "Markets →  Existing / New",
                 "quadrants": [
                     {"title": "Market Penetration", "desc": "Existing products, existing markets. Lowest risk — win more share, usage and retention."},
                     {"title": "Product Development", "desc": "New products, existing markets. Sell more to people who already trust you."},
                     {"title": "Market Development", "desc": "Existing products, new markets. New geographies, segments or channels."},
                     {"title": "Diversification", "desc": "New products, new markets. Highest risk — reserve for genuine strategic bets."}]},
        "when_to_use": ["Setting a 1-3 year growth agenda", "Prioritising a crowded list of growth ideas",
                        "Pressure-testing a bold move before you commit capital"],
        "how_to": ["List every growth idea on the table today.",
                   "Place each idea in one of the four quadrants — be strict about what counts as 'new'.",
                   "Estimate revenue potential AND the capability gap for each.",
                   "Sequence: bank the penetration wins first, fund development from that cash, treat diversification as a portfolio bet.",
                   "Attach one owner, one metric and one 90-day milestone to each chosen move."],
        "watch_outs": ["Teams over-label ideas as 'penetration' to feel safe — challenge it.",
                       "Diversification looks exciting on a slide and breaks companies in reality — ring-fence it."],
    },
    {
        "slug": "swot-tows", "name": "SWOT → TOWS", "category": "Diagnosis",
        "tagline": "Turn a static SWOT into an action plan.",
        "what_it_is": "SWOT captures internal Strengths/Weaknesses and external Opportunities/Threats. TOWS is the missing half most teams skip — it crosses those quadrants to generate concrete strategies instead of a list nobody uses.",
        "grid": {"type": "2x2", "x_label": "Internal", "y_label": "External",
                 "quadrants": [
                     {"title": "Strengths", "desc": "What you do better than anyone — capabilities, assets, relationships."},
                     {"title": "Weaknesses", "desc": "Honest gaps — capability, capital, coverage."},
                     {"title": "Opportunities", "desc": "External shifts you could ride — policy, demand, technology."},
                     {"title": "Threats", "desc": "External forces that could hurt you — competition, regulation, cost."}]},
        "when_to_use": ["Annual strategy offsites", "Entering a new market or segment", "Reframing after a shock or a big win"],
        "how_to": ["Fill each SWOT quadrant with evidence, not opinion — cap at five items each.",
                   "SO strategies: use Strengths to seize Opportunities.",
                   "ST strategies: use Strengths to defend against Threats.",
                   "WO strategies: fix Weaknesses to unlock Opportunities.",
                   "WT strategies: minimise Weaknesses and dodge Threats.",
                   "Pick the three cross-strategies with the highest payoff and assign owners."],
        "watch_outs": ["A SWOT with 20 bullets and no TOWS is theatre, not strategy.",
                       "Beware listing wishes as strengths — demand proof."],
    },
    {
        "slug": "mckinsey-7s", "name": "McKinsey 7S", "category": "Execution",
        "tagline": "Why good strategies stall — and how to align the org behind one.",
        "what_it_is": "Seven interdependent elements that must line up for a strategy to actually happen: Strategy, Structure, Systems (the 'hard' three) and Shared Values, Skills, Style, Staff (the 'soft' four). Change one and the others must follow.",
        "grid": {"type": "list", "items": [
            {"title": "Strategy", "desc": "The plan to build and defend advantage."},
            {"title": "Structure", "desc": "How the org is arranged and who reports to whom."},
            {"title": "Systems", "desc": "The daily processes and workflows that get work done."},
            {"title": "Shared Values", "desc": "The core beliefs at the centre that hold it together."},
            {"title": "Skills", "desc": "The distinctive capabilities of the organisation."},
            {"title": "Style", "desc": "How leaders actually lead and spend their time."},
            {"title": "Staff", "desc": "The people, their roles and how they're developed."}]},
        "when_to_use": ["After setting a new strategy, before you 'just execute'", "Post-merger integration", "When execution keeps failing for no obvious reason"],
        "how_to": ["Describe the current state of all seven elements honestly.",
                   "Define the target state each element needs to be in for the strategy to work.",
                   "Find the misalignments — where two elements pull against each other.",
                   "Redesign the hard elements and deliberately shift the soft ones (they lag).",
                   "Re-check alignment quarterly — the soft four drift first."],
        "watch_outs": ["Leaders fix Structure and ignore Style & Shared Values — that's why re-orgs disappoint.",
                       "The soft elements are slow to move; budget real time for them."],
    },
    {
        "slug": "porters-five-forces", "name": "Porter's Five Forces", "category": "Industry",
        "tagline": "See where the profit in your industry really pools.",
        "what_it_is": "Five structural forces that determine how attractive (and profitable) an industry is. Strong forces squeeze your margins; weak forces leave room to earn. It explains why some industries mint money and others bleed it.",
        "grid": {"type": "list", "items": [
            {"title": "Competitive Rivalry", "desc": "Intensity among existing players — price wars erode everyone."},
            {"title": "Threat of New Entrants", "desc": "How easily newcomers can attack — barriers protect incumbents."},
            {"title": "Bargaining Power of Suppliers", "desc": "Can inputs dictate terms and take your margin?"},
            {"title": "Bargaining Power of Buyers", "desc": "Can customers force prices down?"},
            {"title": "Threat of Substitutes", "desc": "Different ways to meet the same need."}]},
        "when_to_use": ["Assessing a new market or segment", "Repositioning against margin pressure", "Diligence on an acquisition or investment"],
        "how_to": ["Rate each force High / Medium / Low with evidence.",
                   "Identify which one or two forces most compress your economics.",
                   "Design moves that weaken those forces — raise barriers, lock in supply, differentiate against substitutes.",
                   "Choose where to compete based on where the forces are kindest, not where it's loudest.",
                   "Revisit when technology or regulation shifts a force."],
        "watch_outs": ["It's a structural snapshot — pair it with dynamics (who's moving and why).",
                       "Don't average the forces; the binding one decides your fate."],
    },
    {
        "slug": "bcg-matrix", "name": "BCG Growth–Share Matrix", "category": "Portfolio",
        "tagline": "Decide what to fund, milk, fix or kill.",
        "what_it_is": "A portfolio 2x2 plotting each business/product by market growth (attractiveness) and relative market share (your position). It turns 'we love all our children equally' into disciplined capital allocation.",
        "grid": {"type": "2x2", "x_label": "Relative Market Share →  High / Low", "y_label": "Market Growth →  High / Low",
                 "quadrants": [
                     {"title": "Stars", "desc": "High growth, high share. Fund aggressively — tomorrow's cash."},
                     {"title": "Question Marks", "desc": "High growth, low share. Invest selectively or exit — pick winners."},
                     {"title": "Cash Cows", "desc": "Low growth, high share. Milk for cash to fund Stars."},
                     {"title": "Dogs", "desc": "Low growth, low share. Fix, sell or shut down."}]},
        "when_to_use": ["Allocating capital across a portfolio", "Rationalising a sprawling product line", "Setting the M&A / divestment agenda"],
        "how_to": ["Plot every business unit or product by growth and relative share.",
                   "Redirect cash from Cows to Stars and the best Question Marks.",
                   "Set an explicit decision for each Dog — fix, sell or close.",
                   "Balance the portfolio so today's Cows fund tomorrow's Stars.",
                   "Re-plot annually; positions migrate as markets mature."],
        "watch_outs": ["Market share isn't the only route to profit — niche leaders can win.",
                       "A portfolio of only Cows is a slow decline dressed as stability."],
    },
    {
        "slug": "pestle", "name": "PESTLE Scan", "category": "Environment",
        "tagline": "Read the macro forces before they read you.",
        "what_it_is": "A structured scan of the six external forces shaping your operating environment — so strategy is built on where the world is going, not where it's been.",
        "grid": {"type": "list", "items": [
            {"title": "Political", "desc": "Government stability, policy direction, incentives, trade."},
            {"title": "Economic", "desc": "Growth, rates, inflation, capital availability, FX."},
            {"title": "Social", "desc": "Demographics, values, talent and customer behaviour."},
            {"title": "Technological", "desc": "Innovation, automation, disruption curves."},
            {"title": "Legal", "desc": "Regulation, compliance, IP, contracts."},
            {"title": "Environmental", "desc": "Climate, sustainability mandates, resource risk."}]},
        "when_to_use": ["Entering a new geography", "Long-range planning", "Assessing regulatory or policy risk (critical in energy & climate)"],
        "how_to": ["Brainstorm the material factors under each of the six headings.",
                   "Rate each factor by likelihood and impact on your business.",
                   "Separate what you can influence from what you must adapt to.",
                   "Translate the top factors into strategic assumptions and contingencies.",
                   "Refresh at least twice a year in fast-moving sectors."],
        "watch_outs": ["Don't produce a list nobody acts on — end with decisions and triggers.",
                       "In energy & climate, Political and Legal forces can flip economics overnight."],
    },
    {
        "slug": "value-chain", "name": "Value Chain Analysis", "category": "Advantage",
        "tagline": "Find where you truly add value — and where you leak it.",
        "what_it_is": "Breaks the business into primary and support activities so you can see where cost is created and where differentiation is earned. Advantage lives in specific links, not the whole chain.",
        "grid": {"type": "list", "items": [
            {"title": "Inbound Logistics", "desc": "Receiving, storing, distributing inputs."},
            {"title": "Operations", "desc": "Turning inputs into the product/service."},
            {"title": "Outbound Logistics", "desc": "Delivering to customers."},
            {"title": "Marketing & Sales", "desc": "Getting and winning demand."},
            {"title": "Service", "desc": "Support that sustains value after the sale."},
            {"title": "Support: Procurement · Technology · HR · Infrastructure", "desc": "The backbone that enables all primary activities."}]},
        "when_to_use": ["Cost transformation", "Deciding what to build vs. buy vs. outsource", "Finding a defensible source of differentiation"],
        "how_to": ["Map every activity and its cost and value contribution.",
                   "Identify the two or three links where you genuinely differentiate.",
                   "Attack the links that create cost without value.",
                   "Decide make/buy/partner for each link deliberately.",
                   "Reinforce the links that are hardest for rivals to copy."],
        "watch_outs": ["Cutting cost in a differentiating link destroys advantage — know which is which.",
                       "Advantage is usually a few linked activities, not one heroic step."],
    },
    {
        "slug": "balanced-scorecard", "name": "Balanced Scorecard", "category": "Execution",
        "tagline": "Run the business on more than the P&L.",
        "what_it_is": "A performance framework that balances four perspectives so short-term financials don't quietly starve the drivers of long-term value. Strategy becomes a set of linked objectives and measures.",
        "grid": {"type": "list", "items": [
            {"title": "Financial", "desc": "How do we look to shareholders? Revenue, margin, returns."},
            {"title": "Customer", "desc": "How do customers see us? Satisfaction, retention, share."},
            {"title": "Internal Process", "desc": "What must we excel at? Quality, cycle time, cost."},
            {"title": "Learning & Growth", "desc": "How do we keep improving? People, capability, culture."}]},
        "when_to_use": ["Translating strategy into operating metrics", "Aligning teams around a few numbers that matter", "Board and management reporting"],
        "how_to": ["Set three to five objectives under each perspective.",
                   "Attach one leading and one lagging measure to each objective.",
                   "Draw the cause-and-effect: Learning → Process → Customer → Financial.",
                   "Cascade the scorecard to teams so everyone sees their line of sight.",
                   "Review monthly; retire measures that stop driving behaviour."],
        "watch_outs": ["Too many metrics = no focus. Fewer, sharper measures win.",
                       "Leading indicators are the point — don't let lagging financials dominate."],
    },
    {
        "slug": "vrio", "name": "VRIO Framework", "category": "Advantage",
        "tagline": "Test whether a strength is a real, durable advantage.",
        "what_it_is": "Four questions applied to a resource or capability to judge whether it delivers a temporary parity, a temporary edge, or a sustained competitive advantage.",
        "grid": {"type": "list", "items": [
            {"title": "Valuable?", "desc": "Does it let you exploit an opportunity or neutralise a threat?"},
            {"title": "Rare?", "desc": "Do few competitors possess it?"},
            {"title": "Inimitable?", "desc": "Is it costly or hard for others to copy?"},
            {"title": "Organised?", "desc": "Are you organised to actually capture its value?"}]},
        "when_to_use": ["Deciding where to double down", "Investor narrative on your moat", "M&A: what capability are we really buying?"],
        "how_to": ["List your candidate resources and capabilities.",
                   "Run each through V → R → I → O in order.",
                   "V but not R = competitive parity. V+R but imitable = temporary edge.",
                   "V+R+I+O = sustained advantage — build your strategy around these.",
                   "Invest to protect the 'Inimitable' and 'Organised' answers."],
        "watch_outs": ["Most 'strengths' fail at Rare or Inimitable — be ruthless.",
                       "An advantage you're not organised to exploit is wasted."],
    },
    {
        "slug": "blue-ocean-errc", "name": "Blue Ocean — ERRC Grid", "category": "Innovation",
        "tagline": "Break the compete-on-price trap and open new demand.",
        "what_it_is": "The Eliminate-Reduce-Raise-Create grid reshapes your value curve to make the competition irrelevant — you stop fighting over the same customers and open uncontested space.",
        "grid": {"type": "2x2", "x_label": "Cost ↔ Value", "y_label": "Down / Up",
                 "quadrants": [
                     {"title": "Eliminate", "desc": "Which factors the industry takes for granted should be removed?"},
                     {"title": "Reduce", "desc": "Which factors should be dialled well below the standard?"},
                     {"title": "Raise", "desc": "Which factors should be pushed well above the standard?"},
                     {"title": "Create", "desc": "Which factors should be introduced that the industry has never offered?"}]},
        "when_to_use": ["Commoditised, price-warring markets", "Launching a new category or business model", "Differentiating where everyone looks the same"],
        "how_to": ["Map the industry's current value curve — what everyone competes on.",
                   "Run the four ERRC questions to redesign that curve.",
                   "Aim to cut cost (Eliminate/Reduce) AND lift value (Raise/Create) at once.",
                   "Sketch the new value curve and check it's clearly divergent.",
                   "Validate the new demand exists before you scale it."],
        "watch_outs": ["Raising value without eliminating cost is just premium, not blue ocean.",
                       "New space attracts imitators — plan your head-start."],
    },
    {
        "slug": "five-whys", "name": "5 Whys (Why-Why Analysis)", "category": "Problem-Solving",
        "tagline": "Drill past symptoms to the root cause in five questions.",
        "what_it_is": "A disciplined root-cause technique: for any problem, ask 'why?' repeatedly (about five times) until you reach a cause you can actually fix — not just the symptom you first noticed. Simple, fast, and lethal against recurring problems.",
        "grid": {"type": "list", "items": [
            {"title": "Problem", "desc": "State the observable problem precisely and factually."},
            {"title": "Why 1", "desc": "Why did this happen? Answer with evidence."},
            {"title": "Why 2", "desc": "Why did that happen?"},
            {"title": "Why 3", "desc": "Keep going — the causal chain deepens."},
            {"title": "Why 4", "desc": "Most teams stop too early here."},
            {"title": "Why 5 → Root Cause", "desc": "A cause you can act on, usually a process or decision — not a person."}]},
        "when_to_use": ["Recurring operational or quality problems", "Post-incident reviews", "When a 'fix' keeps not sticking"],
        "how_to": ["Write the problem as a specific, observable statement.",
                   "Ask 'why?' and answer with fact, not blame.",
                   "Ask 'why?' of each answer until a fixable root cause emerges (~5 iterations).",
                   "Confirm the chain reads logically bottom-up ('therefore').",
                   "Fix the root cause and add a check so it can't recur."],
        "watch_outs": ["Stopping at a symptom (or a scapegoat) instead of a system cause.",
                       "Complex problems have multiple root-cause branches — combine with a Fishbone."],
    },
    {
        "slug": "fishbone-ishikawa", "name": "Fishbone (Ishikawa) Analysis", "category": "Problem-Solving",
        "tagline": "Map every possible cause of a problem, by category.",
        "what_it_is": "A cause-and-effect diagram that organises the many possible drivers of a problem into standard categories (the 6Ms) so a team can see the whole causal landscape before jumping to a fix.",
        "grid": {"type": "list", "items": [
            {"title": "Machine", "desc": "Equipment, technology, tooling."},
            {"title": "Method", "desc": "Process, procedure, workflow."},
            {"title": "Material", "desc": "Inputs, supplies, data quality."},
            {"title": "Manpower", "desc": "People, skills, capacity."},
            {"title": "Measurement", "desc": "Metrics, inspection, calibration."},
            {"title": "Milieu / Environment", "desc": "External conditions, culture, policy."}]},
        "when_to_use": ["Complex problems with many possible causes", "Cross-functional root-cause workshops", "Quality, delivery or cost breakdowns"],
        "how_to": ["Write the effect (problem) at the fish's head.",
                   "Draw a bone for each of the 6M categories.",
                   "Brainstorm possible causes onto each bone — go wide.",
                   "Use 5 Whys on the most likely bones to reach root causes.",
                   "Prioritise causes by impact and test the top hypotheses with data."],
        "watch_outs": ["It surfaces possible causes, not proven ones — always validate with evidence.",
                       "Don't let the loudest voice fill every bone; invite the whole team."],
    },
    {
        "slug": "issue-tree-mece", "name": "Issue Tree (MECE)", "category": "Problem-Solving",
        "tagline": "Break any problem into a clean, solvable structure — the consultant's core skill.",
        "what_it_is": "The backbone of McKinsey/BCG/Bain problem-solving: decompose a big, fuzzy question into sub-questions that are Mutually Exclusive and Collectively Exhaustive (MECE), so nothing overlaps and nothing is missed — then solve the branches that matter.",
        "grid": {"type": "list", "items": [
            {"title": "Key Question", "desc": "The single decision or problem to solve, framed sharply."},
            {"title": "Level-1 Branches", "desc": "3-4 MECE drivers that fully cover the question."},
            {"title": "Sub-branches", "desc": "Break each driver down again, staying MECE."},
            {"title": "Hypotheses", "desc": "A testable answer at each leaf."},
            {"title": "Prioritise", "desc": "Attack the branches with the most leverage first."}]},
        "when_to_use": ["Framing any complex strategic problem", "Structuring analysis and workplans", "Making a messy debate tractable"],
        "how_to": ["Write the one key question at the top.",
                   "Break it into 3-4 branches that don't overlap and together cover everything (MECE).",
                   "Decompose each branch one or two levels further.",
                   "Form a hypothesis at each leaf you can test with data.",
                   "Use the 80/20: solve the few branches that drive most of the answer first."],
        "watch_outs": ["Overlapping branches (not ME) double-count; gaps (not CE) hide the real driver.",
                       "Don't boil the ocean — hypothesis-lead and prioritise."],
    },
]


def tool_by_slug(slug):
    for t in STRATEGY_TOOLS:
        if t["slug"] == slug:
            return t
    return None
